### ISSUE TITLE
nothing happens on keybind

### ISSUE THREAD

**Issue by soulyouth** [xod-wow/LiteMount#107] opened 2022-10-26 07:18 UTC
What happens?
Keybind doesn't work at all for mounting or dismount

What did you expect to happen instead?
for it to work

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
was working b4 the latest wow update

[bug.txt](https://github.com/xod-wow/LiteMount/files/9867073/bug.txt)

**Comment by mbattersby** [comment] 2022-10-26 07:23
It's working for me. Some other people report this problem, the cause is unknown. One person even reports they have two accounts and one works and the other doesn't. There is no fix and I have nothing to go on.

If you can figure out why it's not working for you, let me know. From the debug output LiteMount is setting everything up correctly but the Blizzard code is not calling the SecureActionButton action to do the mounting.

Does it work if you disable all other addons (yeah i know what a hassle)?

**Comment by mbattersby** [comment] 2022-10-26 07:24
There is a good chance this is a Blizzard bug of some kind.

**Comment by soulyouth** [comment] 2022-10-26 07:27
yeh I'be tried a few toons, all addons on vs off changed the keybind and no luck so far, the elvui guys said that the blizzard end atm is really fucked with tons of bugs so I wouldn't be surprised if it's there end tbh

**Comment by mbattersby** [comment] 2022-10-26 07:29
Yeah honestly the new UI is a mess of awful bugs. :(

**Comment by mbattersby** [comment] 2022-10-26 07:45
Curious if either of these have any effect (just based on some forum results):

`/run SetCVar("ActionButtonUseKeyDown", true)`
or
`/run SetCVar("ActionButtonUseKeyDown", false)`

**Comment by mbattersby** [comment] 2022-10-26 07:51
Probably stick with the first one. :)

Thanks, seems to be a known blizzard bug.

**Comment by mbattersby** [comment] 2022-10-26 08:21
LiteMount 10.0.3 has an attempted work around. If you feel like checking whether it works in 10.0.3 with both settings that would be terrific.

**Comment by soulyouth** [comment] 2022-10-26 08:39
works with both now

**Comment by mbattersby** [comment] 2022-10-26 08:45
Thanks. Gonna close this off now, appreciate all your help.

**Closed by mbattersby** 2022-10-26 08:45 UTC
Labels: replied
