### ISSUE TITLE
Dragonriding mount not being summoned in Valdrakken (intermitent bug)

### ISSUE THREAD

**Issue by Holt59** [xod-wow/LiteMount#138] opened 2023-02-19 19:43 UTC
What happens?

My Grand Expedition Yakk keeps being summoned instead of my dragonriding mount. This does not always happen, but is very common when I get back to Valdrakken / reload in Valdrakken. After some time, the macro works again, I have no clue what makes it work when it does.

What did you expect to happen instead?

My dragon riding mount to be summoned.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?

Never happened with the latest version of LiteMount. With the current version, it happens from time to time, especially in Valdrakken.

Please do not modify anything below this line.

--- General ---

date: Sun Feb 19 20:41:41 2023
build: 10.0.5 | 48069 | Feb 10 2023 | 100005
version: 10.0.11
locale: enUS
current profile: Default

--- Player ---

name: Irsia-ConseildesOmbres
class: DRUID
level: 70
race: NightElf
faction: Alliance
spec: 2 103 Feral

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: 10.0 Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: 
IsFlyableArea(): false

--- Debugging Output ---

 - found 2 mounts.
 - PriorityRandom n=2, t=0.667, c=0.656
 - setting action to mount Mount Form
PreClick ok time 21.711299998686
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
 - trying to clone target's mount
Dispatching rule ApplyRules
 - checking 4 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 2 mounts
 - trying Dragon Riding Mount
 - found 0 mounts.
 - trying Ground Mount
 - found 2 mounts.
 - PriorityRandom n=2, t=0.667, c=0.603
 - setting action to mount Mount Form
PreClick ok time 20.890699999407
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to cancel Mount Form
PreClick ok time 0.14629999920726
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
 - trying to clone target's mount
 - setting action to mount Grand Expedition Yak
PreClick ok time 2.2335000000894
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.09180000051856
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
 - trying to clone target's mount
 - setting action to mount Grand Expedition Yak
PreClick ok time 2.0740000009537
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
 - trying to clone target's mount
 - setting action to mount Grand Expedition Yak
PreClick ok time 2.4006000012159
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
 - trying to clone target's mount
 - setting action to mount Grand Expedition Yak
PreClick ok time 2.0447000004351
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.088899999856949
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
 - trying to clone target's mount
 - setting action to mount Grand Expedition Yak
PreClick ok time 2.4048999994993
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
 - trying to clone target's mount
 - setting action to mount Grand Expedition Yak
PreClick ok time 2.0488000009209
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=false)

--- Options DB ---

DU1Yos2rU1pNzHHnI3p8oPwYAK1Osct1Zy4nfQuDLv1juwzkKvwZaPf1)J)o8pMp8E5H8kGbtBPUx0HI
lJiizqE4Ji1DX7E)D3(HpU7I8VF9LdV8YHDVD))6B3)UZNEz)HJVD)d7F5T7)UN)Hl7FzH2ZNE8Wt)19
xE5W5t3DZ8URY6(9SQ)BzvF838YE)pE4019x(nVUV83VW9Z)oyZ)4bzD)Mx27pC6WZ)V)p)wxhw5thp)
d7okF)LxF(5ZNE35xpDvO)MCoLk17UjE3nPyTwhRdhJsEDyU3MXeggW42ygWCTr)UB6J8D3mA4lP8CMx
ioM6XEr3TqOIzB6ST1DRfM1IsBQhWz0QlhYOdILZPhhP5cfZwzgxgvw5RR)dKVBpC6LR7o9HfXh0C73S
74HNF48fSB1u6UB)R7E9413U)8JVD)1pU)T7)6tFy3Lt7UIfiu0U72p74t7V(X)Woy38zFy3d7F(NV7M
AjG7P9hp(4HlyrV7Wv8HJ)7VD)7L942pU7kSZ2)WB3)h3D84lcVc6F)(N)PJ73Cw)NyrG69x(P9NUcUt
ud3If)W5)(ZNpF6T7)8xVCyhUf)Ql4g5HxesIGKV4YU9Nery0X2(97o9Woq3D3G)JVC3l4KXs)MdNE6H
ZpVifrOhUz)XRWx91vXckI)8R)Wp)29)Pdpcw47pFw4Y4Iy9LpV)YUJG3)Il7398FFhe3yRkRy)1xLT(
6zS97US7x(4Utl7wh6croxfTV(0JVUQ(JHw5UB)2Zp9kM9LJGpXMU7WrCUFg27LlzCGF(LZ)4(tlKiA9
AgZ9DVEvOx00qGF35dhFC3PNOc(VC6H9x(HZpHtVuWred)BbHF390zFFYzQmLLcwE)(FArBuXvHSlF2V
8QC5TybS8byo8vxw4Y3F4zHGh(B4Ibeb2yGv9T7E6GOEF5pak2F5YUpSFzDnDdV58p(XxXQ)UhFC)Pxo
83K1bJ8Ll(9VCDLfOm85NHD5HpiAHApkY4RxudXBVU7IOikP)jgzF(XZNXz9FGReHpwCK)PlNF8WX9FZ
(F(L)FbkF7xS)XfP)tHd7e(PGEDk)KOToPFsa2FfJ(pft1P8tbJUHt)uiNgPUoErbZPXWhpU7P3bhINw
rAuCr8H)8F5M7U9FbRK4JyUB)V(6VDDY)Hywpl4VF)LdNVC46bf5QLdjImwA1viWLzxHNZZCSVozOlMK
RKggP0kG7SeNReKYPY0jDDYCVeYRK2IL6kWAcm8iRFpeRoLf7qxJdeZnWmRlQ1cAGICS11ZFHGIpRgry
0gPvABTYW20v2l3YjLNHqxckHZ8SsbPgmEsxouYnL5h1HU6EPTkrJroRYwomkfNYjL4yqjOMba26Wc(R
pPYNTPPNkPHgyBu6CsCzNt(WSt6k7xYZu3)UQCkia36guy42zRpguIvDJi7RKfBZznPloLZ6MN6Aqv52
upCrpKm9WkH1yjUoxPTEiLEq)xDxtie(6O6mPrFJJAGNkMnVUKjsyO5tgnwPBc)i6Fp5ZUoSo7AUczC5
h0pNBuuZ1sK3UZw2vfQrwAovdYLvLmPw3uCLPALwBu0rHyuTdAfA5cjoOojskqRCsdoEuNMcDvNodTzW
2t1BQ1dQWbBGW6gvg0zTNBQAegHHUEK96iBxZQnaYXH6o8zLpsDOr1H5QU7DtHjYRcve6t9CGdYuDvld
tjeIgsrPwDP0ydOqwhws0VcUVj1cEzyZjyLtRQav7RNDdCMUlZb0mRFe30RJA06Oz4ALcbZenrIsAuL5
ATnjQhe)Qj1v78AoLQaoZHq3KAxaJUrmZcnrV9Lj7uuh6vkW3uCLLVVUvZETfSJ3VYAnBndtWNgFywWk
G4ymN0SVsuYuhinfBZjEzGukFU7lsTXktdBofv15OtBiri1DFg6rFpJRRbEs5KVCnL7rk48HY71Ctbxf
grLxa3x6BMT70M8zP03tuHcuE9sO0PxvCZfRY9Zbz54ei)nNNR2URaYIGQEdZaDMaPvIEnRnghOaEwfA
yOMTdDvqGPsLONDDo4xH6Iwg2beo95Rvw1eSBu1aye1OT6HnLObmwzIroejUBhEYoiv1Tq5kZvNtZRet
QIrhEIQBpckRgJBQKd)rnLZHkmHDszAbX0W866Ey7mnEKdZCUv7OYmBIcOKAVjXEXA2iamzbOkJQux6m
0SmPRPDbuTdGrwA4uQwKJPRiP6lsBmH5uHtmn4QLlkt7SEoW0IrLXMNcKYGAKulu5V89i1y1nx(EDYm9
Nue2ZQ0LaV4YKoue0Ppz3jLaHHIMysg(dSk5YCW0vGiSskSiJ01UMhR7pchQaqILetrs(UlS05rgAX5O
1pGls2rnZBU)yujWSd1rnXSXaSOhWpRwslu2mUwXEkw2qYNvJw37Dz9Q3lcTRXLA1cXHKvn8v18HUArx
uiO2)ralhSTVN8Hw2AeMqCF1HJIzux97YQFxjD0WNCyhVZt1nlsTq7eCsMuvAI6HGKXIfvc4XmO30q3k
PzKjaGCixNfbbMmTCyxh8vvDsRgd29jvZYPQFwwEX)8gkzA5CnWxJw94pmuCYqS9w4ihPELvXUVUiCnZ
4EYY9dI5dwhbnuBuYek60QhaIHo9ZsbvIi(VA0bOIPt50P0U)PRMSRm5VSvUqhHm2SkMWksdV5BGlcmu
rf5gN9LPM1naT43fQlyerLMvFZ2Oe2CeSKfEfi64n8fd1bNLnRFyRNGeTyEUHduuOcsLO47WWNT6dzGx
epJ5gf17(LVRg0aVQ6mg1hEZ(YZsIPGGkHA(KBwf32HfheeKc2X6Qwn2JCJRb3610gDaruqXXAoVG)uZ
ezNikfr)xwdJDc9MUtJaJYdoPtfBOsDrgbbTsqISCJLH0rpKSsDNTgtADWtdaETT8GBuBfWBvlkqz(HX
6ILWsm1Qqn46invdHhjQCRPzYiDK1YLy2S7(w0DM1tTJlwDo4(ZKga8sOBlsVVrXidlXxMibsuH6n2Ay
XJLz)lLJZcL6e0uy0MZOdomnCUtVbGZf)ETA5SbTonr61EqtPmX6rx2QUDQeQhAk9aeVivuIWgxfQOvA
SSE1AoozdmqgcSIrOikE8hD7bqlJebZMOjFTOVPQdFpXsZXwLisJSQKVd6S4(NUEZyM5kfzb7y0S4lQA
lAdc7CdF5A4Spz3fRn7fJf3ABwVI7la)RtIYII(IAbtczAdsjbB0BRCOKkXMvzzWwy3d6iBhtcyJNaKQ
2IdulxT77V5z2yCB4mQoPnuDFZjD4BQ5SK4PISPyiGyDAnFcB70jO7dvve8YjsAiLvCIQfKbgXdlXIKf
dUPUGa)UK3m7QYquXzNbR2onCk1VJ61dgprqOCyA1Kj9HJ8K13bKnu2p)UVkM4hVSxwVQRG5UETv8Myk
SYgX3CIInxR1t(Xw9L56YoRYa3SrNGHTVv3CqLbrA2q6MdtLM6CtGr2DfXkGH8daiRzlt1Ia8rXjw(UY
Is)GvvxmZcTY9q3Yjl2S8pWEL9LHztIgR1nSqaM4xzuLk0QltiDZ(6MNdg8oeuxHi0ydEtn6uNNHBVsB
kT57BzxgsmZo(inEHzvubxYYQTUudKBZO0W7t9mBwMSOnA8vD3St36EotjexDzNWbpOUN1uylNq7tMJi
W3I9nhQclu5wbMtbGaxWsSrmE1MDz5fJtOnDN5tS8Dv9GRBEzjeSUR1rJTthAARB4ZqH2X1abRRSRhlF
V4RsfQbccmTHeyVYc3IfCwdt(vkLmuvrnBjyk7kdcwsSm5iqfiheaWSLbP1KJ5msNzH2OUzZQ126yvbU
qTxjQUMSkfOUybTaQZatIMVUSR6TzVsGRCjYMqHyJ6viIDn0gkG8eM0UZ6XJyTPoIWALj0uNtnoBgH(y
zMOmLyY31StGzUyT5HLjGqKMgcuQam1Q94hqfxS7agpkjpqrWNvjawjztb5jGs4fz)h(SDBwl036BOld
ZWht3lPoyAV4pKFfj5hnHrhvqX9Qgajpejl0TkDqeB2QGG36EPzY6KgWSq5W)ox00bCytmHBYGxrOMxR
)aw7JWwrBmHuwRj8ZmDCHnJTTDogebPrSzRyCCuaxYPvTmrTteNdhAR5e08nBZrqhPjrZLRgRgtRAE9N
)GWHOmf(5cZAlez36b2bRB2SbedxI4IiJSaxCdXIfMgOFmxyENWcOZK9AWEHEbqdUklW1IqzcPBQTXHh
umDXHK6qHwMxy2AmeGeYEUgmbLcQVCDzcqqu3GH1qDuxIkold5LasrZntiJJC7zg3I6msAtmVk5NnY0h
w9HGhLOQ9aBAVKzIEU9sYcAhy5xOqUcDkYSZ547mBTLxMI(YyxDdjgDUjVG6kbsWb9YV2Subakk14SNE
Xq270dnZ8F3ls9Jk7l6vlte6skhFWYAjZw7dfhZ1jrBpP7GQvQ0PjtX)RZEp5Is2hQqOJ5GMCtRvvsrt
jtu3KYTEwGbIEk1D3mIkB5rX0LHs50lMfvmtUaBXQksAf5MSBjFpje2ceKLtkFUl4sA1nHag6n3ss7uH
IqTmmrFyEfj97sJVOBhImejVWG(cUitSd1Tq7Lb7S)YZwqeeClr1rWs(meYmQS98qyVyFoqI02t)NzRD
XbusBstL34twGWYRqOQZjkJURsyvtlskrtdzNTkJLn1nnOYeWISztT6iSXkGPF3nUoKyPenMrUSPvF4k
)p68POWjXNiaAp2f9LCPurfaJ8QQZwGcnn)vcipzpTYrLwk(ec9nTeCj(Lukd)UKT163HDdFqva7Rrbf
mNSbkz9tfcnTmLx)ZY7IVoG)oHidReJNa5Inuazts33cFhJfMDJ3jJyzDRdOTLjJUfT0UQt7HEGBe963
KkGKILNqDKhB17ZZK98OIS)N(jOmgCZObHq6GSR1QjyWUUTaiGVfTe0Lwbt2(CjBWn1g0DET7BQNYmbG
q90mLEHd2Wa0pa1bmCM1mZPQ1nEk8fUf7vpvhEXKtexv6V12sXIKRSNuT5nWJDfFXGvNfMtS498YppVL
dqEwRv1Iy8ROtIX7gDTEBM4VlgjTmcwdELohiFs(W9cc9kTfKnxXvkB2vVsk(SbOqpvPnlSzzl7QQ)yT
UrptnR0rHm64NiiYYMZAZSF0sf(BgyrLq2arv3C9hvoI3Dsw3UAi4YULIrXE9fRGnju4MCLnKlZstmuv
Bs(2lYEQLpGcpz6Ej(JfjZ3ysE4bM3K80B0peM2Q9uky11jvpqdcjm3kTWr1EYUqMDTqkCtTn8FeTl77
kplqO6KiJrRQOsDZtkZYAeKtvxbCjwTgqqyCYS9JWbGG8(r6DZ6qCt5pVmX4fqYb9O6BATe1wX82(Zsu
yytQ8cUiyckf79BXfKEtu6jNrTBGjBcrjeDqVI1RheTKPrBvH3b)PMxW6rDJMj(29YPRGBqoRUDQzCK9
63s8hQM8IpQxK4AnCwvNfPIPIV0iyL)L2rUouYKJjWc0zMAsI9JdO7Q7iRxdsMYhIxGLdj3Va7jO8ZVq
vSIDk9XcEpbTxcsUJ0C2LFAkrLjr9WrYemXzaKOZnisskv5RYdZMIdkT5xGeJnhC7A)YkZ8ULF)okhlw
vuzMhd3wQXi6dIeUqlbOrXKEg0BQ5rfFPrvRCAWYIrSpPjwN(Gs8rRDar6fV8ZSHYsXQ1uOv9B6SOqa7
Wq7sNj68aYSjfsdtudJI9U)IZMV)8Nns1EARLE2qJeR8mP8n3XH5rzTAx(1uQs9yBAsklNzL8YZFSEIc
StYYnM9hO08F(OER1KFtAQIcLn1nwIrsbsebnKcKwgoSF7oI)btKitVkGf2TxhY(jxvA2RmeTgmHGR2J
rg5pKILnLirfMKVSPQ4nAzRhJL6MlFfSESjIp)HIX)xBOSQqB2Ii6jkwvvZDTkiulIQAfvhdXh4p92LU
oseTS97(ZEelP8yZVsX7WnjVmfJDTueztDXKDqawyCvshTvhhGqOMGipuwKP8iAQHbcEObbex8Lrx1)E
3)h

**Comment by mbattersby** [comment] 2023-02-19 23:38
I'm 99.9% sure the reason for this is the "copy target's mount" behaviour. A lot of people in town are on yak's and if you target them  you will copy the yak from them. It's not a bug but you can untick the option from the settings if you don't want it.

**Comment by Holt59** [comment] 2023-02-20 08:06
> I'm 99.9% sure the reason for this is the "copy target's mount" behaviour. A lot of people in town are on yaks and if you target them you will copy the yak from them. It's not a bug but you can untick the option from the settings if you don't want it.

Thanks, that might be it. I have the Cliffside drake with priority 4 (always), so I was not expecting something else when dragonridding is enable.

**Comment by mbattersby** [comment] 2023-02-22 11:53
Assuming that was it and closing. Feel free to reopen if it was something else.

**Closed by mbattersby** 2023-02-22 11:53 UTC
Labels: advice, replied
