### ISSUE TITLE
Rules to exclude ground mounts in flyable areas not working

### ISSUE THREAD

**Issue by Demothrin** [xod-wow/LiteMount#271] opened 2024-07-29 02:07 UTC
What happens?
I use keybind 1 to mount a random mount from the groups/rules I have set up, sometimes the mount is a ground mount which cannot fly

What did you expect to happen instead?
I should not be getting on ground mounts when im in a flyable area as I have got ground mounts set as excluded when in an area I can fly/skyride

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
yes, 10.2.7-4 this feature worked fine, the issue began once skyriding was added to the game

Please do not modify anything below this line.

--- General ---

date: Sun Jul 28 21:01:43 2024
expansion: Dragonflight
build: 11.0.0 | 55824 | Jul 24 2024 | 110000 |  |  
version: 11.0.0-13
locale: enUS
current profile: Default

--- Player ---

name: Malkuriân-ArgentDawn
class: HUNTER
level: 70
race: NightElf
faction: Alliance
spec: 1 253 0

--- Location ---

map: Townlong Steppes (388)
mapPath: Townlong Steppes (388) -> Pandaria (424) -> Azeroth (947) -> Cosmic (946)
instance: Pandaria (870)
zoneText: Townlong Steppes
subZoneText: Niuzao Temple
IsFlyableArea(): true
IsAdvancedFlyableArea(): true

--- Macros ---

```
```

--- Debugging Output ---

```
Initializing LiteMount v11.0.0-13, debugging enabled.
Got refresh event COMPANION_LEARNED
Got refresh event COMPANION_LEARNED
Got refresh event COMPANION_LEARNED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
[1] PreClick handler (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 9 rules for button 1
  Dispatching rule Mount [map:424] Pandaria
  * args: Pandaria
  * limits:
     1. CASTABLE
     2. Pandaria
  * filtered list contains 82 mounts
  * setting action to mount Grand Expedition Yak
  * found matching rule 9
[1] PreClick ok time 52.65ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 0.32ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 9 rules for button 1
  Dispatching rule Mount [map:424] Pandaria
  * args: Pandaria
  * limits:
     1. CASTABLE
     2. Pandaria
  * filtered list contains 82 mounts
  * setting action to mount Great Blue Dragon Turtle
  * found matching rule 9
[1] PreClick ok time 19.94ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.01ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 9 rules for button 1
  Dispatching rule Mount [map:424] Pandaria
  * args: Pandaria
  * limits:
     1. CASTABLE
     2. Pandaria
  * filtered list contains 82 mounts
  * setting action to mount Blue Dragon Turtle
  * found matching rule 9
[1] PreClick ok time 20.41ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.02ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  Dispatching rule CopyTargetsMount
  Dispatching rule ApplyRules
  * checking 9 rules for button 1
  Dispatching rule Mount [map:424] Pandaria
  * args: Pandaria
  * limits:
     1. CASTABLE
     2. Pandaria
  * filtered list contains 82 mounts
  * setting action to mount Azure Cloud Serpent
  * found matching rule 9
[1] PreClick ok time 28.81ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
[1] PostClick finish time 0.02ms
[1] PreClick handler (inputButton=LeftButton, isDown=true)
  Dispatching rule LeaveVehicle
  Dispatching rule Dismount [nofalling]
  * setting action to dismount
[1] PreClick ok time 0.25ms
[1] PostClick handler (inputButton=LeftButton, isDown=true)
```

--- Options DB ---

vYx2oYXXvB(4OFdyBKrgBz47O2TLujcvuAaSHlWKDxD3fy1vrKD1sM6c(S87bZC3S8amxYxS5S9DISP0
yRrc2DOiJLZ(werTlS7f72E1DZl8F)M5JV(XLdV))6P39Y)W7E5ZwUD)PlV7LF68pDI(8f6F3E7XZVA(
ip4Bxo)4BEGB9SFE)Y5l3rn3ucPCy3hVBtRMhKgJtJLPrUvyigAzPVCUOTILsRiFnfsXXOmUXW04GmUA
OKk(C1wL4WyYNH0xCyAmlZinwP)rALMMuqzAQ1g0HnglkqfNszzBB0wjRwm1APO(XH2uvBnMcJ2ud6xd
0suKwTOT90MMIc6esJP6K0QgSTNBLmqkKJ(2R4W4Wqt(yj0ueSeO9x(gTPJzDIeDYOiPsWAn1k62hItJ
vB7hQrDU0YXqoXY(0L5BptC0)8dh3Z8R(h3m2gcrfbNsnfTsHqUKF6w8VHH1X1WWG2AfR73id7xJn5yB
iNRjPVylng0fohttnLEcowNpjJB6P0NibMHmAf)a2JmJ2hqhDwl)vvQSZ3DgKSi6hNQ6UgP(QgmneuUT
SRO1yX4pBoVC5UL9NUw4ne4Rdj3iAo3OMjTkRNAqBuBsJ640WtLEO9xX1AmgucX4yA0AOKRYqalyX4c0
UQevAqkxOmmO4g3JYWZcIvttzf9R6ajQvwBqJuAus6ij4mQ443(4LJZkggicVPEtcjqptNj9xLANQJ6k
bEdjielRGcEKgV3yAtehI)ByOcPIXXWtXUXymQYeDvrIQytRfv0WiLg(X0Vbm06A8RqMoMu875eYnVCy
wqWX6yZ0cHuwkvizfzFi49dLYcJXGzJKM7uX6ZusP(ibnD9GIljsNG1YujRRxSKu5d5RjF9QOLQctq1q
sLcDnngshM8wnFvuHIsZmRtS4QoozL1wbgSumIyxf8vyflt(eW(cSS1IJ(xXmmTezL95gY(4Q(QyJlL6
WCQpdVpv4MTNQg0eAG1xkB0EcMdvFgMn(wkn5qAYPgzhs99WmTXTCEUQt2nKkFvNR79qmgI9iNDQXGbb
JdrNUyUuyjc81qO6WNVhQpcs2UQQcSuxh3gHCqeCqID47B0H(rN)gIoem4FfgWhM8vUyYgdriHrom0vH
PKD5ERpwUtNH5PN0G(S73VmF8AkAJL9Z3lMchjFo66romH9yIXOWmbFU73rJlmwZQCqm3Mm)aPPq5dC2
19NYRxvLCgZMTbsVCsP48(2mtitQEPee0dpE)9Np9jNF80fXHkbavIcTjSdo03u2bnyYmNA7it)H6LWD
cg5XAIz8ynVAYauMlnqE1MihQKLuymDdHOGuklSParaTlGSH3jEBYkirERIKu)g(lSCLT5A0y6aypeBg
hCzczaQ6fnhxzsap16gd0THc)XaC2W7GzsHCW5kaB4Dr9FlWGgvXgfGz7EYaiXYGrcdKkNbztfoonUP6
ZJHG6eTkjMcPMBuATyDtiLQtEz6LHgztHCzTdHMW7LPQWuv151MrxowWbYn7GrderAfQeNikg0MktAtv
MIxkZWKWjmvqPT6PY5SnLIAXhHDEqfzmZWstMvmXGaCBHXMvkTgFWgMUB2yfoOzdHhS6nLj0ACcYyn7D
BmUQqhlcIWMJ4f203nYkBSWyqJYErnRTXKYxTGavHv1kmpcnQAzX0iIf0OWr6PkjsuvY3vJbB4)xSmrK
tTBnQmi8X(R2WI8MLLnmnxD)kufnWsLCRXyTXilS0UaGQbvLYsJ2bebMy(QgyRaOKCFHLBc7SWl0XMy3
xY(P2fermnTbHSOXJYYc0SIqhxC(Osq1jMJgf1ejayvJrcpuLXlIoltpkIkadnM33nmgAjUi7mjLo6cf
bZoIg15MPDWyie4dQKajPnYIhHDiSDDab1ufZuIPOHCKYztGGDwuqk3NZDrKVutRQOT4pvmjz5QjGdhu
fgHeDI0unWQS)wUPkGwgicrxcmuvafFJkVxJJNHxnMurW1sVGiv7GNzPTg9NigOXEjybzsRSdY(XOjMu
f0iylMkyYKxJoPXKPMl4avvJWAuzmfXC(laMMxHA8PwQQbdlEhitoAKp1hLiXzEcf5Al2jF0k5XYXrMO
MKJO0rITvJBzENH5qEW1DiodigWaNzOHPLXDweWQ4hNFHqR5mFhCHl(78G1GWvdZs(lI8Gg(3gratDfl
azHsOJrbE50C72Owd5wIMkd6dDsScKAcmWkQzRtRMGkgjbuOuvjw0nI6LgNMAHttWqGygikkLYsMuMjP
tQgQSONfG3IPwaIOAprybssEMTSbriVzqCZTNW7TmkkKfMeLzaJKaMKLjSdHKBQstWQKg(MzSUPY8AMx
QWTguSygutduimKDsyDrckv0zOppgDb(GrdLCvajUPw11mCeWkPXKl2wswimwC)c5rdxL7vt7tGkrKsT
yjjDPSBAO6iTydfe0kCGG2TQO8nYrqD15t3C42Fy)YdhoFIO372E40dxMpDLwHIWUTF18Xd3F95LDBgO
GdNF4Y(LtV7LF1Ht3E957FyNyLz32Nr5np)UxE(M39YND60H7oCC(ISIbwuElfI2Yf9ZBVmV8GWG2T9t
3V)nlpsl3lwOqnzXHm158T3UF5DV8a1)L72ZL9A518hjpzB3E18YX90s9nNpjWYBjYida)5R2F1Y5FIM
ZNC4Y817pYKiYQ62VB)Lhzi(YzcQNxM)57MzWkqsBB3(n)abVhpEGr439YVyEz5WdCjA(69)4(JV7LIq
CLGPp(45ZxF)8JuFBpoFlT9hoTxq(cbuFZ5BFukRdL8jdUho(wUOD7NzwpP7T9hOzAOVGr)xMxUE)Phy
2cXG3(SJ3U)YDF0mH0p7kc2V)TY(sFz7DZxF(NU)mdtF8JuETea8flu8Ux)aRKZKWdl0c(n0gStcAC32
Vy5W9lemqqY(3C(cjBqYt9eJzcjHrpJwWL9)eXgzwY5L7z644UTVGHVp)8YT7n215hpYiAH5xpB52hfS
M8oU9zp8GHweW9xNp9r)4(hEqacMY(63s4)v3r)3tuiE6Y(dhoD9HRMNxy0loyK1vC6TNo)tKo7uMlb6
Thy(7dFejDSFzz(Q9S5NelFS8ALI85ZeYZ0yMj8I5tZZuN)LhpD7X9IWebhBM)rMM9XZxUCK3GRiX0Ld
NjI3eV9Zx96BMVC357zI1(38GaybdC3ssu7V8Gsh(U5B3FJSDfYz(2xO8cNJ(jlp(aX5imlZigkZYMmf
Bjj9F44nZNU9prOcp4V)enYxD(w6ZzgY3F)B2)ari)kceWy(M9xrcQkPI015IhU)eRf2ebxwU4p8CgFx
Riq(b3(LZhpAW8xF427UCIyXcnQOKU72pZQIV4Udx969xyfrwpC(67HenfGkPMD35JNVNvl4OaI2CvnG
UcwGchC7xQlOtk(wo5XVG5RDQnho1VKMD389VrmsuOGf2(8dWcX8Iy5G8ZYCc6)WKfFXDpEsPXuiP)cQ
kPy(J0FEUOyrsDS1I7woGjRcyQKEM8AtW9XJ3iApgc9NyU89VHWgAbeZw9kcUPjsXeN64617VqZJfuwE
Z(txefdAwSELjGsS1dKaitQiR7BF2JxDhPdq6VSLEYx12WWFm8hZegC4EAH(Ud3WYB)H39YV8hjf0)Jx
yglyzPh(DeqqUl2AAdku8zNU(iP2rWWBwugnN0X2VMiRFe17xttu7UYsAF(Y(9eJ9AwFMjbFfZoFXHLz
HXtUsiJh7j63fHK)dhos26evjwM(twE7BmoeBF48Ll7nhbm5ITD0nVMPGw(vjWkN6osDC)YEserKwjNA
0W)(JxpFVABMT0)mw(v1AFo5lzVikg4Wpu9wIAD(m9))Lk(WbeTD7H9WU13UClzh8EwbQrPtUv48eI94
f1WNOWKzteRuy2YiUOdOMSiVsNx2ZeYpNgeXqE2VJ1Yy6ejjUm)AXDpBy8vet5Xh(9qmtmBZ4hzx4QdV
sThXGU7)YqCQ32tuH(89miZvk4)3chKx7hfd0)hp7NVNAEAVawrHg(OyZGZiB73F6wYN8F(0TNplUAg)
LEI(ZNia608fw1Vq5sVMA8D7V54(Rm34KNUDB)lZhyV8F68rItFATcEoxxlE)NyxsNM)dV489VI9urF8
7M)5Zl3iImlI3kXpXF9XJF0NtUDzsjN232VGGL1kS7VCr9rX6mbo6DL9VCMfbipCxUtjkS9jcFwo)e4A
CCeo1uMIOkXudkstT)N9ZpYYOcLHvXmh6F0d3XO4ZjCLL84SDFkcY)h02CGzYKMbtaz3V)WHZkdwKlP9
Py7ZMZV(UhjrIV9gIk8WHFKTSMz20huXnkitoKJ2FCGMZZ)mIlVz)praYX53YHf9z)J3SFruh(DcE)z)
Jdhfr0Vd(BP8oFILkIgEhTbhyVZ504)cftZF8NtIucspYjUU9z3FyHe2F4HdhHaUaP8M(LNFdpoot0T)
vsO44EIj8jKH4f2kaL1WVU3Tp(mfJjfkaBNLM53F5woIiDmAWQFiz5NMFROTm9eUJW0uZ9m7C)XZ3sQH
QUc70JzAB2F8YDS0Gzr8aRFWhHezO(8R37hihNqD6jEP2E5TQMBi8eBlBo84ppFMJlHjY8QvBgt(Zim)
vevKJMnW6eK(0nu0WhFIq5ahB3NtCarA8xi((P)08YnmvLHNNEQHSAmhu7JV6TS9XByRJNpZwskS57vQ
3pBHcG4hzDx2pJy(JI27AXi3vVM46meYrF(0OxF(crcjpkh49KWMtIZWC(de(vLjMC(Q3soEUCNwq23S
C(gsC8R2)w5aP)09)8cjlONITaclSdfQ)BeTnCq3Z)kNZ9VyqV))8F9OE))9FZR17)F)VzuV)F(BETo8
()B)gg17)F(BzTE))JFlJ6x)EbSg6)p))dO)F(VDuV))ZVT169)V(xoQU4HjBODtnVNlG)ZjvJLdKJEn
XtunPD9sdSJRhyefdYQqeNNBlIQunuZHInlVa6JTuWsPNlNsRpuTZiLpCuhAkPfxnSZUbfYKMAdtwk11
busBEsjF)TC77PPNsTXIv6YsziRdigkvuwFESPEV20SJTGhWuzYkiKx8GeH(5AFdAoaGAJwrTDJu6CTQ
pRckWJEyc8I2wvs92ubeiCAfecA7ArRDdtjMYtg0XvXrAnnfTkTnghMsP(iBwZwyWgqogS6(nMKZ6aDA
KhRcROxDbMsv0PvLF0mILAQAysSzvuw(UrE5dnsxGKXhSdEs7Y2f5cdaAGo8qP1qvEtJXOTjer2eYsza
em9y0Ph6aZHuWKRk2(gMgQwtCqvvBdgrPQJ5MuDtEvNYdEzMBe9vBsSMQcHOaz23doawDsZuO)9XEVAt
(0CmjVycyqKKDgSrglGweZPaedAfdwzALjpp2AGaYZA0jlMQdXBRfFRmSNVybAN6LHqMEjb9fIKmykSw
HV5rs2da9xlei3SnuA91e6a1bdLisM9zz3RC5SwFmCPjyoPglg1NlGMXTgR5POlEystLud0z6Zg0T6mi
5t(RH10OOmbXSRnuTQhkaNzbXoknJGaBzPCUJ7oyKgSsoMgHgkQ5xqSQmwl9bO9Mnekx19UqqMTkTjIE
PFKKkSAGcjPs3iCcMBzkXiWu7K6qHgnun7BsP)zifWOLoYwCyO6yDhbdDzFdvSZifD6O6KXOj1AG)831
LQvZM2odjDwwP4ZzYr8MdhUiUzC2QEo3xkdl2uSFj7yJ4R6gFArd6(aB3qWtgzTpFtCl1CVh2boZLSdI
tm(ABuBawOKnQPBeT8bVtwkHNNDohO3qF9vCYoxqJG4sHbiINjZJbhOnYeo5i0BTpwJJyfDhda0p9mq4
b4h7tmHJCG8Z2LsmKU52IdnYlKpL1REn50htFQna1r)0QOV3Yf4tYoWBUjzcWKTcKuF03Ff9i5UmmMxT
(yYJjUwjplJ9on6a9v70Yj7WG6Px3GGin6rjyh7g3lL6GXDy6q1HJ(YdAlpsfoZTg025onzp7Kdn800U
jajAY7mHYaLa5Bn7OxQpseAuyCY1RR9GuIqMK3w38HjEMArhPOrcskokrEoRqfCaJSxxd)tvegb3zN83
rvC(TK82uFKMC8uRtsbHmazqg4mKJfDWSzwMtC09bh7LU4JdyKdgDkNaBq(EauSmIMHwZCh6G9XqcNoi
buWZpUOckqddCHS7(k0DKpsyGh4xkabTHKfAvK0ImKHJMdbCjxvoFwgfIKQAMutihG1LCCcgMltRgzP)
9oHb(m4MUVyO(qwSgDaOb1lk25cONe2mzk9JiktYincvPMG5jwTbHrZtYOrDRIKp4Xojc2z6wfKfWSkq
rLyEml5ecGHNfciEA05mEiP8sv792C6MTsddMNhkwWKbFbYHYGV9waE4YwGE9GxZRMFZ3uy)QFA88aWT
Di3fhSBIb6DYbWoTkx6F3qGkSvYDoPUnKM6gO3euTviLCFjnpg1qWDZ3CtWPXgUXoKfClbocOrmM0caz
ekLhCoN21yjSZpNDSazhz6SGXsVzTpuTxYkWqF9t9pBZNVaBbdwy)DQ7sEat9byswnSOK1dOhpkhgI20
9ghxLfaFvnCGgSfcs05tYIiSbEL6GpI3opn4zQriqOpwZ3bfcccvKNMoGaf(Kj61psAEKT(i9GMGfdEv
re1rpVTQDBMSzzQUrkpOsFb6OaCoM5l3wFAMUxHSBI0LLd0eKRuNhBQe4cOGTOZVtROsRGbt6CcCoMF0
6tAfo0z9RUGgzqLjBcR2axrkb7ILGNMSDNVWynnHukdbnEXM692rs44K7fX0Rx5oEDdvi)x4l2sFOMgk
zzp3XhqYT7uh3uVI9Ycm43me9w07Zcl7KhrHEr6X221qRDXAlmgzbmmNe1S4mQ5XvKoyV1UqvbPQHM8j
V(Wio8PYchJqvQHRchLFmIIIGVk4hdzqS4BfLNBzajpYx7SvgEG)Z8aibuOPfe7xwJsx6TcxsY06kwjO
elx3uP3bVkcS59oi0RxYOhaefnaI4Di)bxZldj6fhcjbz3XKGOfwCbj)U(W0UG)DlSj7z9ialjZoQPFm
swuhQ(cyIm6nYxg6qnNHdSaKoPOgb9oarAYedY2JlKJrnhQWNcd)Lo8pHMGSXanYoycFhx8LD9RqftFY
1bl()ruQcCbQSnfHsq0pWwiDwdPOiXrsTbVak2fAY2utiJcxdLnGijMQbZvTLNCI4bQKIoo5Qd2DoIha
P6A(3xDJ(wFZzPinqaJKub0JBHicCnGY6qTAP(KY(Kw5rOHWk4RHMbIituzw1oATATMC8k070efyhvAN
uwWH(KSDLXqexgN)2k6McHCaARMfIXVKAiUpkCshdqnp5BnRXxiv(AF9n2ktSH5VsXuOlLgU2GCIpL(S
wXJCTPraauKRzmn3)kPK28AzsBwRVUOPCL09vWno4Mm4BqEXXgt0BkGWKzkxFokjKmtLmVJ0wnGCNsUJ
f7(tBR0Q90(EU6rwgr9lWvsK7nX19fWKxhkkAYyF)R9zH4890N4RC74Q1YOMfptL(DYMHQsNs4kCHsNQ
vh7qqUpTAFagpIn8h6dyYx3Cx0XqhC9iTHUAZmel7v2MhakAkjMGWzggcq4HMMrqj7ui9c(7giwliI2r
kipVujd1ANk4XwrRvSpn4XTuDZMdiUdzSP(yTPXdDOp2qFSM1K0WGP2eikgsxinvbnpsMiSXooU671vl
BxQePXX55BIc97p4yooyPHnM8tBHS37IQUxc7o4IjTI4RKXwfwdKR0DOpuJItUggB9zbzXHgkgAglfz3
AiSATwbRqUEm2LLHhv(Myo27n3Nfc8N3ndcGbpApHFkkueZGPSu2QsIeWAbURNQkIXAjFdgdxMv2Nfed
4bO7vEQGJwI4HqDFQbBer(UVKaXiTsRyQp0uFbmIXe5vQ5nHNMSxPlkeE4jLA0l9kspMJ232GypSCkE1
yhyH8F)oxh4hmsFV8Cp8kK1Ab4kKhAWOgukxk2IhkHTxnn)u(7o)eIXK9w3IwWTYWRQjAuZW6zmfq1o5
nWq2mXUd2QwAqm3lByO)IyKHIOzIiUmkHQgm52kavO1cH0ocBbY8nz3SMv8GnwiXwGCUe(DNeAPGqPpK
vIrR6EW5otsNsZbneWiYUtI2ShWlQZeTOW8pbaEwXE5EtCAVz0C08)LZ(PwsC(KlLaV542DhKsJGkayV
zhmuyYUn1RTDe5XrIgWVfPtahKv5WogKMd(rGQpOaP5y0pBVqCLuIHb6RktPb6RBH)obnq6NpEl3uqYZ
sRogaxELyerVSXAp5adAYJ91T6OoOc2ZdHBM9djK8w5LyMwxpsj9o1lqM(YC4XYLDQ1x3shgmeohXrzG
3FdgB171mZKIpPPh6AcCcPxygzk55gxYg5JJCBvYMWszzc1A1EFCCV9ZBn2TsWjAb(t39DC0RJiX1TGR
z9zJ4sthWnzkp5HbJsui92rHKlolNDmdfCojd9En1qkIxulZH(PIQV6cbeNGNnoceKoA)qSg8GzAr3uE
bMpLrczTE03CqGk2kpRMCFSi20u3xXuantJU6sn4HptQrMhIuTFwU9nqFgGcjQHR8GSSqSLekDL7eyy6
t9ugqUZgzImudBskKdsWbi4w5nJ6l1yFKbZ8uavdD9BPIH2CFSk)cp5HD6H2zQf2R6e7qQdSqxyaLPMs
qGVlvY(sudyGZEVib88jycx0l0fVOqbJujcDyfrctz(GaW9lZax(EekwdrgY2d8AXHutj7fsLmyrp9bc
YJKVD(QuK(7pbi7(5T7zwZsgMzHHao)ykWcVk)fipoYzsyafxuftpJ0J8KLOim9SPInykNTjQdWnKkEq
IOtKyi5meXpskCdoSmcBr1r)1yrbph70ktk3EQqCZgFsuAt7XSPBlQglznSACl8uCuU1amDQVLhmuJWo
M9Zpk28H6pRuzOg3CmIZSG8CNrWKKTxlGGejUyc02BruM1a8eGxytWi9iTeQtpk9eQtT)e7M61zCaNA4
yXlggoGBkopV2ddz)sSWNcGrPS3p5oPAYO4lzsXiO9gXzNS(PhZfVAOVSDflKLcZ3c2AXbvAnzdKoMIC
x6pOmARQ9RdGP50k9ZXyaSDMO6oDJE1V0x1PmupcCP(Vwexe1aXhtPvc1D)unZ44ffJJgtLZbo2XQvj9
zewsA0mmWEcmmHJe21h9LLfBSCCgHm(ufNjVKGAhumFkSPvtMG87H01OeGCj8CgNLldGMzw2MDY3aeIK
x6wzV0zXhBAZOpglHc4azHo6vrA0R1qi1J71l6A1JSNptvdHjTxp35ue9YHyIa88lBbzllgDP22kXlKh
tZtzIKJGZr91)f2P(iCJTfVY4Owfs2pMbK4aU8cKUqLtxMDhf96iAp7pPP(A)f8Yd3MmfonaHIIxNu8K
NvrvtMZEDW7EYZ(JnMPRQ9i8vYcoOIvVpuoCEdxlEau8bXAGAlIBqtSFU0SwlmPmL6)GbGltdNLKbOC6
e2qh8Ko5haeoYYeKoyUc20uYJRVm43eG4WQde0O6uShUJXP(rmLWbpKW5VlqQVsHU5vuMrc6RgrtUVFE
9Bgr1e4RIhSz2ddMVin6Iz)AmOlGFRXKFya0M8DTibOP6PnhM6fXd2157SikVjHxgExgrwmsY6RIPXJ6
AYdpkH0KIvYAwTVS9WbrYWtzC6gc4o1hBp(d4tn5x(krLsHr2kksaCev(MTxL7RQhhUhzlNKFdOdSmB)
KmWDouG23Q3Fo(HwadyfPXeF47Kb008hAV)yGzgzeN4r)b2kS0GdTWNWy1VyBC53Hn)iUKNSbGshcGmr
2pPpktceCCcNUGSQ22YhT2uhcqVEn04Ho5BLXf5kw0JRb8Zgu6zHRvbMAw6NWr0HF3nKvI8Z42PZdD83
dVW)HHyyYpME((Ncf0wdH8hClGuUu43TdosNIgTlVSWPi5G2TLGWMSFsscQSPFMuJGQq4sfx)lYAciMS
DPP(Ycv4gU809FTg4axmIb(T4WwvZRzb6CPcUL2ID9vEdSMTsXmgjw7bDXJ2l3q1cLAicreyIf)SfWDs
wD6NkxXPRJ97HG)trahmWQJ1cMZZ4kkXx2wKGpfwZOs4RKhCDBZPQFwu(jyZeGvfqgfTY(HRq6LCZ6cM
JUVXgUlgKvuePFBexmnE6wikKKh6mdMjzvdkH(VQjIswgjaYbon1bwOMs25nKn5Cg8dNIrIk9KImHxkn
H(51hR9ygqrsin2mIsj0)QfJO)BAdFTdXXXfXDXHm7pTcqN6WHXwtU1t53cbZOlx9BteMO)wnVI2pIfQ
7EdtPiIa9N)jwaolQU)w9hybzRirudwiBJWmiFMsWHDyAnW26lRTxdWmO9JPKTS4GMyndKZiFiY6KQi9
u2Nc4QuIj2(p6VKb8tbe3K0b9CwrbXSFfgWi7ChuwkgsnHzk7ytwI9ePZIdz04Jn)3ad87rZU(VlfS8v
m7hlse3PzgPWDZEGYzhkMOae4xWcDda6tUeHjQaoDl8l7sq0pIi51QNrPCPdmR4LMNdw0psb(GZ979lT
UPoeyuGQLqe5QpTUKxMhlUaCaUGnsPeFE4gOQRCyGgu1)1vIZZ1DZf87eiV)glIVMbM5ckokehxjo0ZY
Y9ycV(sfnHP3aKwJKHjeizd1NLVh8MZho(GQVPM2q1s3IJnaYpuYyjh6WZxHV7GwwI2VAi8ScUaKCGir
aPt2oHFZn0v1dZEOnb6Bdf9G(heLizSyWnMf71Un41YXlHf7NwADz32LhpIFMl0FRl(6d3F4YN9pU64J
8Jr8VDT807woC98RoU)3FZX3Y)9V)Ux(DF)gANSHVLFSN)TtNTp)7pD(jtddpYp0Uh5xf1F7(538NiLI
)o)Kq93xE6d((qG(E)NrGN(vcZhOp)HpC0YhSgKYcboRMWh8wcRFW4zqc)gYUz6d(446p2E6hjPJ)o)u
zTFIjK3611677YEwxVL9kEr(3D)F)d

**Comment by mbattersby** [comment] 2024-07-29 02:46
I think the problem is that `Skyriding area` and `Flying area` now both take into account the flight style selected so your rule which requires both conditions to be true can never match as you will always be in one or the other flight style.

This is still evolving a bit, I'm not sure if it even makes sense to have "Skyriding area" any more, or for it to work this way.

I think your rule mostly only worked by fluke before because they were 99% of the time the same thing. There's no "OR" condition for rules, if you want it to apply in both circumstances you'll have to make two rules.

Happy adventuring, X.

**Comment by mbattersby** [comment] 2024-08-05 12:20
Closing this off, I have plans to get rid of dragonriding area which will make everything more obvious.

**Closed by mbattersby** 2024-08-05 12:20 UTC
Labels: advice, replied
