### ISSUE TITLE
Intermittent LUA error when activating Litemount via keybind

### ISSUE THREAD

**Issue by jungheeMW** [xod-wow/LiteMount#269] opened 2024-07-27 14:44 UTC
Getting the following LUA error when attempting to activate LiteMount via keybind. Error may be related to https://github.com/xod-wow/LiteMount/issues/264
```
2x [ADDON_ACTION_BLOCKED] AddOn 'LiteMount' tried to call the protected function 'LM_B1:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@LiteMount/SecureAction.lua"]:48: in function `ClearActionButton'
[string "@LiteMount/ActionButton.lua"]:89: in function <LiteMount/ActionButton.lua:85>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```
------
**Additional information:**
1. Error is not consistent, but seems to have the highest chance of appearing when activating Litemount right as I exit combat.
2. LiteMount is activated via a keybind (in my case: T)
3. LiteMount version is 11.0.0-11
4. Error occurred on shaman. Unavailable macro and combat macro are enabled and as follows:
```
/dismount [mounted]
/stopmacro [mounted]
/cast [noform] Ghost Wolf
/cancelform [form]
/leavevehicle
```
5. Error occurs right when shaman shifts into ghost wolf form, as the player exist combat.

**Comment by mbattersby** [comment] 2024-07-27 15:10
Coincidentally, I just found this myself and fixed it before I saw your ticket. Should be working on in 11.0.0-12, please test.

**Comment by jungheeMW** [comment] 2024-07-27 19:34
I did some testing on my shaman again, and although the LUA error is gone, there now appears to be a very miniscule delay between me pressing the keybind for Litemount and it taking effect. This again, happens at the edge of ending combat.

**Comment by mbattersby** [comment] 2024-07-28 01:18
I'll be honest, I can't reproduce that and I don't have any specific idea what it might be. I guess  it could just be a coincidence and the server lagged, or maybe there is some issue. It's hard to see anywhere in the code that changed recently that could affect running the macro in combat, it's basically stuck into the LiteMount button when combat starts and from there it's all Blizzard.

I have timers in the debug for how long various parts take. and nothing seems out of whack. It takes about 20ms to choose a mount (on my PC) out of combat, but the in-combat times are 0.02ms + 0.02ms. 40 nanoseconds is definitely not a noticeable delay, and honestly all those nanoseconds are probably saving the debugging info. At 144Hz a screen refresh is only every 7 ms.

I'm going to close this off because I don't think the title will help other people who might have the same issue find it and I don't want to rename it. Please log another ticket if you like with as much information as you can provide, but unless you can narrow it down further yourself, figure out exactly what LiteMount verison it started with or somehow luck on the actual trigger, I don't think there's anything I can do.

**Closed** 2024-07-28 01:21 UTC
Labels: bug

**Comment by jungheeMW** [comment] 2024-07-28 04:54
Thank you very much for your work. Yeah I'll chalk it up to latency issues on my end since it seems to be working fine for you. I'm not getting any obvious errors and this delay is something like ~0.5s, so it's honestly not that noticeable anyways unless I'm intentionally paying attention.

**Comment by mbattersby** [comment] 2024-07-28 05:01
No problem. 0.5s is an insanely long delay though, if you figure out what it is please let me know.
