### ISSUE TITLE
Group names with all numbers don't work

### ISSUE THREAD

**Issue by JPHILL1992** [xod-wow/LiteMount#46] opened 2021-07-05 16:17 UTC
What happens?

I can't check the boxes to select mounts in the groups menu. I use ElvUI.

What did you expect to happen instead?

I expected to be able to check the boxes.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?

Please do not modify anything below this line.

--- General ---

date: Mon Jul  5 17:12:09 2021
version: 9.1.3
locale: enUS
current profile: 1

--- Player ---

name: Thandrior-Sporeggar
class: WARLOCK
level: 60
race: BloodElf
faction: Horde
spec: 3 267 Destruction

--- Location ---

map: The Maw (1543)
mapPath: The Maw (1543) -> The Shadowlands (1550) -> Cosmic (946)
instance: The Shadowlands (2222)
zoneText: The Maw
subZoneText: Ve'nari's Refuge
IsFlyableArea(): false

--- Debugging Output ---

Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Got refresh event BAG_UPDATE
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Refreshing status of all mounts.
Setting flag 1 for spell Acherus Deathcharger (48778).
Setting flag 1 for spell Acherus Deathcharger (48778).
Setting flag 1 for spell Albino Drake (60025).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Dreamlight Runestag (312759).
Setting flag 1 for spell Enchanted Dreamlight Runestag (312761).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Black Drake (59650).
Setting flag 1 for spell Dreamlight Runestag (312759).
Setting flag 1 for spell Enchanted Dreamlight Runestag (312761).
Setting flag 1 for spell Black Serpent of N'Zoth (305182).
Setting flag 1 for spell Arboreal Gulper (339632).
Refresh
PostClick handler called on LM_B1
 - setting action to in-combat action
PostClick handler called on LM_B2
 - setting action to in-combat action
PostClick handler called on LM_B3
 - setting action to in-combat action
PostClick handler called on LM_B4
 - setting action to in-combat action
Setting flag 1 for spell Black Drake (59650).

--- Options DB ---

TZzxV1roYz4FqbbO53K(UGSi3eSobqdYLcRgBzpcqwAISCs2B2F7PQUR36T0STNZi75InFmgyC7(WUAY
Iflwf5d7Rtx)dxF17(PBEs)7F4NU5H3)0Dp(0F5p93)x(tx9Zp(0TF8Jh)07E8HpC3h)3U9PpF3JpC9B
BxF1xE4)4M7U)MF8(B)J38UNE86RU(z5px9X7F8hV5(ZFK7E4ZpFZdV72pl)8BZY)PVYBL30pDZ7F8)8
E5L)5dH8Zp94hU7(B)NV9p)5FT61vPqH3l5F42pCZxU)z9Yp94xE45)v9PU757oELLuBwhx)2KCzz1l5
9ltLwnn3VmpNJ62XDZ1wZUCRKwTJlhTXMD3zjLoewUSg9U9yBfRSQS6uahxMBZEz)Q2CnlwDjxNhcTSM
BwTQM3gh)Eox2SkyAUwB(7CGQ6inQuuvC3IjRwRvsh3mTj1pV6zT6(idr1xRw2EbI26OaLAV1oKQOHQR
dbuAIgyzTQYiLmHL3Yw7QpSkG2SoUxTSYhkTuzApDAK6PoFAR(VnSMATMAj2s7OI0mzU)8w3AllL(Oa5
v1UR0uTUY9NY6k3s5PPRtZrzWcC8gARfExTvovynyWx7rlOVLkhfTMh2pV3uWLBTU)mzRRUKZvtOsV6r
LUVM5o)5kFOeVRv)LoAu)K7clriZ2AmB8XZ8XnDYyBfQiMLqzTLOs16hxZbeVOsn537MfrBm5dGBDOwA
Mv9intB2Dy7WSZ2FoRMQDoM13y16MDwrSJtwz3kvQ9nvvEmH5L0P2QMe6PYkOboESQ0LbtLHvP6LPPPl
B9kmELF(4M9rX6CZRwzg6inLMCz17imRpTlfJJYwZBVH4wKvmGAjdppEgzeRvLkPEhwKY1hYS3tzkZPF
pVdBchwQhnwplWnXAzU8uZmu0m8Ijv5PpCEBIE8TI9QkzX34rnvE7lFO)AGrCI1t1gqiYYK)QUnOuXDN
DZp7Uupkqx8xEuRfBRGxQmRP27ugprNelkYJ6XAaZSwQMSwCAz97YqL1Y6zfLxf3e(YNP5CqrAVCv3Xr
JLklRzei(k9bMTuXgKS5vzTOHAQzKL7fBu4UyBEzXD7BWhf9HuNDmDWMOstwfOSzoUsRTogBtNiAlaE(
2kMHG87RmLkQG96WKQoZg0gI(Nd1nRZ6wccqeR7MwSPnl1kgNVpldRlygxPbeCZvmtnzCeCROvwtBwXC
hLA1ARdX8ZS)L(km8q(VcMNVVbhcYKG2tj9W27Vi15jEQfS62FQJ2ImZSn8vhCB2)ItiOGflvZwum72S
2)O2GGK5tnh6Y0I2a5Cx6mrZBmdfDWIcR(YMpaV2O1kMzU2mLQoK2(zr6wvUlUR5e3M2vhtDur0rfiUL
cCyvAQz5Hm7yY(Ke2I14NfB4JmAfUgeRuZ3J6JYEKKeEG120b5iyJYaoesAigwbW0AAiy(SvIU1Um1XD
3RPf)Pyf9Oj1e9Tj(XQBV0vbZLPdOSOQe7zZR)YJJr6IXK)dtGfzk95M)Z24Ywd6WuobNPIZs8gtTXaA
UIpYxdjZ(9L04r3L0j5v5zh9Sfe)zvMIaDI5(eo0YOBy6XzmeFeyiM8pmnU8MS(ZDZfmNyTJwvQw9rRZ
rJff6IMvP0zpdU93yjPVvmhIyJUW7pVTyrnfG(QSMAsgzA1QY2QFCPeYvdvLecVw6bAqSsSiMlD5r28o
1MpCDBHjXe3PwVU0d5Hs17Obmt9Gpc4rxCDD8QgTMnmrT4Gt2EhZYiHAHWZLUhmWwQPvk0Llu7T28aCu
V9Wh4s8IB(BZJmSZ3g5gRaEmawOq9fc0rIT0JKtA9yeNeikJ1YCMwe5dRkvPz6pPxXAvQFtpeLK5zB3h
5KcWEQMxd0(kZSrhQLOuHc2dyPPDB2nNBMwrIKQfcWdjiunpNI9rQ46Nem2lIzfeABeMq1cNOoS4sKWb
8jMkDB6krrxh(DBj69XKVmjnu)YReDksonjRnV52FQuZSQo9xGh4RucZwEBlHbJZ8YET7gd0dLnUPTHS
gKqHrwdY46qUenMxeMrrMLYSlKrB2OILeHkCkNTFwgtwrZBalHCbdvvD6rTxmJ7iaVT4let26twjPmIu
IudvZ9r2Tn0ohtplg3DmbFVXNbnDPlXEOM7iU5dteVlfm1Je1J94IbN5BqROi(wjQrtFmxuh4(2l(Kay
YI5cMaA7bH5Q5i5JN8O(eBu7MsmPfws7s1jpnrpkPykGXOAjnJ5QmbB2BBf3DQ53sSvRv4JzYLiyM8Gd
8WGwfKbVyRzElKjAhiFlzM8ONFRPkMO2O15SylCGgjlY2sY730OYiCBeIeY6GVjByB1hIOtbu8Otx20f
sWLl0(ZilGKKWq1D2HLnrIDeJRfpOwpXEn1kAZxIep6hDM5IhZCXeLwvXuSilLD7foXVNVsAZdid3DVl
hwUtxPlPZGi6KSjZi8FK4QmxbAtQ9CO(5VRUh7Pef6XtTNozMsfXjx7ORwkmkAQ5Pzkrh7rYdFKsOhne
XIiGcL6Xtvr1xClHStA(8gI(3uAnjnbpsnKbSO8klkrtrxG)xnCAVklrvydcRWoqhXyptdjwSKgxYE6L
VquIYRt3ZwVNALAICdPOmS5731XykXulKGRfSCrtP3YkOoSzeepNiis9HSlfPpWKNneBHAJoOqBOPxPl
nRgvqI47MahVOK8R2uh7DBfxlWgSVojRQ7qgz9kD)tepJwuZBGoe1C5MAPcR(nVrLHFn1gIvaKnGmEdI
vdLWflI5RHSI0X7yEuvby1WgS72LkIyyIme3RSMd6UVmKDpGpmACVC2plzKHLhquQlV51yjrVRezf9kJ
UKrqMw0g6YfzDPQNE4awMm(43L(SCqMD)DI4oK2R5Gs1UwK5B(sykQrpWVTbsVVwGYt6OrMyIfh8e385
GLz4TM3sMIN9nWPN8qMDG611SIxtSEpIPpmtW0H71tBO4QIiq1HQiQQcYhwc0z4b73GlHYeZgNLW3Shs
Ze0Jk17ILIc3NZTbNicr9v8gI8wNt4)DHSKLkODtvLAkVnjgeZ0U6RHMyy6jiicfgwyrS2RQH3Vnkl52
gYvis)o6Bh(KhQ2ZueDeGI2ZH4mrSDA1Orf60lO1BkkbZdGusKqQwlHdIcgQQbmEC1sQeMsuSAHf0ALW
SHBIpltjQH8BM91jw7Bv3dhy6k0yUfRBiHDXDDhHkHzB3x91JcMLu7rCnPUV2658gIrP18z(wnUIR1Ip
jUVUtUZkD(oK9L4GO4(9q4iIxjKDYqTtVgAvZGwxq3JBkQFe0Ok0d5lchX1jX9ytNQRR1MhThwzbXmfR
GK2LJuEKOsxuQi5fPRgZCUTH1lPOlsQvTft2bLlA3dpKbTSECEyRa0ARPxeJ6uOOUaYBCais2wvmCsSj
BemqbezCZDUTn8m1Mdo8p4x3doAWmPMy4NeJnUuF9STclpjbaKHC2Dtpu95(vTksACxQ0JkhTGytP)Cz
QcF2Km6c31QUNSnB42Uud1kOjwyDq1UimAwIvbwb0ROy5zrhPrAVXa9XkUlolguQwTvM(aM(YmNw3IQx
tSY6)EohuSiwzXebXcVHL3thOJWhevODtzwHchBahFArxUyXA(lb43dL9OIlzdN8HSizc5EwAlA3HvWC
M73X0IhBxTfKjcoqYqcdUAB0Wcky5QJNxgpYDqBISavVBmTLbcCusmabYjQv0uLml8PBq4pY0krx3iqT
o2q1DXAJCu7LJAOmDJ50BnC7nnsRWalyVjw2OZAdPNkbhvXYaOvwmHJKTgCkj(mSciMU(Q7nG)39Almn
8yL0bcDw0db0tiuSD3aw7sN8ZSmKGjDN1zKw8(88iCsSuH7oqdgSMna0ayuO2Mc56If9pH5Cu9V3tGyw
xfpMSIpHydUU76oVtjA18kxwRu1hPLnZy1xKzWU8vWApqipbcyYUl0Lxa4UEIb1dzSdEtnZGvJ0XeVmt
)c6QQVE9AuMwTxMoXuRzUujlSOrRbwEi5VrxHkt7PRdSr8AAKhxwrVNMUo8T2WVQAte3Q8ZW8jJuEMKi
GHeKNfwSxhxibznFkpzoSJIs6d9GYAIXeybm2RLw7zWHriEIsyTinJT5yYLfU77csM(mttgND2JAJ7tr
Pa7OXgSJ0yuy0VbSaSoarj5RWThoZUqn9ztYSXQlI(0c3XJNsKtfzgkA2TgRQUFiFbm19wc(eXwDOBh7
XvljYot3xlz4zOL9DXuf6afaZfVNNUPYLSeT5VLGnr0A(2HvliwuDjfc6um9x1Egj7ymrz3Z3yFnBt4v
csi0TCb0BSVdeuQhVQjwD39sI4MsakgvLAJyfxWMDWC4lGN)i6C)Mcv3M(bLP1G322c2OM03An4TFMAC
lWW6BRvuKbQOXZUN)I5UQ7izmtyH23tb2kz2x5VL4jetr4DKDDdDPmXCeB433vQqaDSvaAzRWqfMCkij
ajgDjLOwf7GKk2Slw4)r5oGAledTUr2jwwpSXksJwRcwBuY41v9szlSSHXv0Np2g)cCASxuRkOJaMuSt
kwR9irI4R5Iperl6cTHkA6YODSi(IzVVmpWECxQdVgG02tsSqW6QJDDv3Vp8yQYT61wRFqxFcKQIe2uQ
r5E0iLGtrq)QUf)UUM(uSDkw7LvRGgJDZ2GppZSUTqYy6(kBd5L8(GJYbWJPW1isYI3Usxoz2j09SQSw
LUMx27jvbDBQiX40c6533iqFLjqgK77ZL1BjgxMlXf3H8KVQ96uEBSKbPs3lyPDLUq3id7zMYC0HoB0Y
hje881x90xoG37Tj8)u0bF)DpF3Jpy3)QpDZp)M9uGYxF1N)Yp(PBF6J3((RV6XF(6R(hE7FqLYnVtl)
1x9hvS)K)5tF0F2NFJAfRGfkp(xt6P9vLve)hU)pRqnkv8RV6F)dV7nTUU5J)2FvIdQ9xv50xfqG8nkr
E)2fAnDi06Pc92)RNF6M3OKZPA)SD3FHE6T)l)G(Eo5vkT)NE(V(9E37FJUxGpB)5eEo)W938X)XF6Mh
(4r)3r8A)GIL5v)DAT9yh(c34Ww9f3qNAkCJJi9c3Wa1K3zVUK(keEg8u(7kHNbGPodWZaVkNb4zyBHj
1zNd4jJK4Capd(ot)neGNC6()pjGNmgNeb8KUJ)Fm8DsV2)(H3zG5LZX7Kmx(AW7mSL3jI3zmaloVtGI
TqQiNr4zCgmhUOiGNCYUaHNCYWaINmrgc7zIeEswIcZ6EgHNbked89eNl)uepdXFey8meyqaYtI6X5mE
gWtG8Z8DI4zmwggHtaYtgb0VzipzIRbomiKNH0OcuEs6DcmnLohYZamSmsUyewFVuEg3O5ZX8KeyhyH5
7fZZiLKeqK03cMNelMqm0Nt5jPlia5ziC8lq5jZsigypPunGgnrgma5zae4aKNKJxc5zeOwMqYLO8mYS
iZTjqQX5yEgsjICEsKoJ5rrmsJK3WJasi9Stj9mKKlj9mKPxG0ZKV)Hov9K0tYodpFke46yUN(SBHCtj
flbOfdqOYSgiL2xIYZHZcFaZZqc1xGZtMfEm3CYg2PGEga4Ll(cxBKWXy47eZtcwhXEnq74PqEgx6Ila
5jpoebW4IqEgwLKxbKN(QS8Ay8Ki4ey8KKm)IfrXz8Km(saJEfmEgjWlW6eX5Jli03gKNH1dIlOftJpa
26PmE6lswGXZanQbuS46TDoINryDCcbd7RFCP3cGFsepd0Ogq8K8mhwdX4k(rwLsNb5zaI3xSGLNa5PV
0ExcXtUYf8uaei8mSAMbyuZrI)jJNHfzmaMlr08uepNV4WiXyQlHyyTxfr8mWvFynKpfXZiKU8i58nW4
zafpc5zIGdtARoLXZaQ)PtH88fhctNFVaAObkpDJ(tP8mGgkP88fOF6tPXLWJlUzy)bc7AW5GEg2HHVf
qpdyDFoPNXDGGKEYJ0t4GCe4elWQxyhucmkZLFnG6zyZgcOEg2nIaRNCTbj6VXZ1b3xKaSNbgJcWEgXv
Mh6MaJMbApdiQsApd0btu2c7Gv4O4CkUNbu4C6Id0EgimLNyJWEQ9nr7j31TWw29AG9mSPFb86c7piPM
R6HuaoEof0ZasDe2(aQNC3kVaQNe0yYJh5T7uqpd7ukpcwK0ZWMRYDCna6j5W)eqpjlEC7CdCEswRpfZ
ZtXZ7syEg2GzY5zafViONHDOMSqhqW77N0ZWPXIWE)7aPNoXFC)4dGhFoPNb2)iPNCt(dKphOzMekhr)
ZPioG235WEgzm4eypFjncirFc7zCd)jTNbaIjCYboKpN2tscyaqpInrISueX9mayCGAVoZhfuk6Bt0zW
Es6HdWsudGjYH8MJdc6zGqqsMCMNdfc3pb9maM7fb9K86sopdeeFbopdqRqCDpfZthQys8sadMaLNbmz
i8meZtEebiMNbOHjMNbkCEbBoKDXVbopJO)48afW8mGybjjoskSpGmqWBKwrhZZi4IKsPiMNeJPlI5za
(jcMlPTnGtlP8KiiEkKNbmRoLYtYT4fH8KyCDrippLD3asyxKXZayKeU2VnepjEAPaHNKo3Zq8KWTfz3
La7g4GlGj7xHXtpMUatDbepdWq(BMXZag0rgpdWSErgpjeRNZ4zalWarReBWiJNeDvY4jjx9vG4zaqXe
r8mGBAeXZaVPNrO5RbXZtzenG4zaYsY45VahZeRRvwbW0ANW4zGStI75VaCu7D6eMEreptes2adSbizt
KXZDv8KYftV50)wcqdhOkMuEUlHgLlsIWP8KmMxcqEs8QD(TdqD)vq8KG3hqipa0pz8K0WhqKpao)UuT
bxEsAEqImJ2e57KNlPu4uKqgp5PqjCcc(1z8KNDI4rR4mgpdhYJaKNHZosGYtEkusKYtEkwseYZWzK5x
hYZWj0jq5jpmp8S(eoWzeYtEg1oLXtEa5oLXZ4bXJyEgpquoMNHVzi87PcP8CxOM(6VMYZWXGKuEgprK
oKNHJzz67GYZmpAZXdMkP88fNHv)8Os2nVeLNHVeo7sfD1(jZvnpXyJFvkpJhA4ZP8KhfWWzfKuEgoPZ
NI5z4ScUlvZ)6zeBEcKNz(HViWMj)IlSlspwumqZbUmq5zINmE(LY5CipdNbF(vcis5zg9dHtpD4Bxb3
J9WNdGWNwGWPDnY5P)zkiropFX3hg)tFW5CEg(GQf48KFrhIGEYJ2B47mr4dvredzY2B8JIXPOE(Ypoj
a1Z4x3eYckpN0HVBiHVec8dqs475YRH0ZWh8M4hvL0fi9m8PlHKEg(sVei9KFZy(kGEYZpo)q0eOSKF8
A4x8g(zrJF6CUiLNHVetNt5j)IrfacLF6GiJNHVcrHV3pVggp53KjI4z4R)0fq8m(DzX)(4XV8vKWZWN
iS9n3fdi9p1kKL54x(lI4z88x7FnXoNWt(Lmu9R2Wv(kI7Fa0cNYC(rlSqOz()j88)nq457(YNF(Xp9p
D)n7pZo2Lp7)56)7

**Comment by mbattersby** [comment] 2021-07-06 00:57
This is a weird one. I don't think there's any way the WoW UI can be different for different people. Perhaps it is something to do with ElvUI. There's nothing special about the group selection buttons, they're just regular WoW UI buttons like hundreds of others across the base UI and addons.

Do you have the problem with ElvUI disabled? I think to get any further I'll need you to figure out what addon is actually causing the issue.

**Comment by mbattersby** [comment] 2021-07-06 01:01
I tried installing ElvUI but I don't have any issues clicking the buttons with it enabled.

**Comment by mbattersby** [comment] 2021-07-06 01:36
Can you try to narrow down which other addon is causing your issue?

**Comment by JPHILL1992** [comment] 2021-07-06 21:53
I've tried using litemount whilst all other addons are disabled and the behaviour persists. It's weird, as the hover highlight works, and I get the mount preview and tooltip etc. I just don't see a check mark, and I can't untick mounts either.

**Comment by JPHILL1992** [comment] 2021-07-06 21:54
I also have another VERY weird bug where a small icon of a random ability is displayed in the direct center of the screen while I have litemount active and I'm in a group.

**Comment by mbattersby** [comment] 2021-07-06 23:44
I think the best thing to do might be to uninstall and re-install LiteMount. It's possible whatever updated it to the most recent version (curseforge, wowup, etc) failed to update some of the files. This has happened to people a few times before.

If that doesn't help, can you run

`/console scriptErrors 1`

and see if any lua script error messages related to LiteMount appear?

**Comment by mbattersby** [comment] 2021-07-07 11:37
Eureka! I know what the problem is.

If your group name is all numbers, it doesn't work, because LiteMount thinks it's a spell ID at various points in the code.

I'm not sure what I should do about this for now, but you can solve your problem by renaming the group to something that has a letter in it.

**Comment by JPHILL1992** [comment] 2021-07-07 11:40
That makes a lot of sense. My laziness has caught me out yet again. Thanks for your help!

**Comment by mbattersby** [comment] 2021-07-07 11:56
I don't think I allow all-numeric groups without breaking people's existing configs. Instead I've added a check on group create/rename so that it won't let you create them, which will be in the next release (9.1.6 or above).

Thanks for your patience.

**Closed by mbattersby** 2021-07-07 11:56 UTC
Labels: bug, fixed
