### ISSUE TITLE
Mounts with / in name can't be used for rules and actions

### ISSUE THREAD

**Issue by dxkota** [xod-wow/LiteMount#122] opened 2022-12-07 01:10 UTC
What happens?
When making a rule to summon only the Aerial Unit R-21X in Mechagon Island map, a random mount is summoned instead.

What did you expect to happen instead?
For the Aerial Unit R-21X to be summoned.

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
I have not tried this in any previous versions.

If I change the mount in the rule to another flying mount, then the rule will work as intended.
Reloaded UI, Exited game and reopened game. Restarted computer. Disabled all other addons to test.

I changed the rule to the Azure Drake and then summoned it twice and am including this snippet as well

Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
Dispatching rule Mount [map:1462,nosubmerged] Azure Drake
 - filters: Azure Drake
 - setting action to mount Azure Drake
 - found matching rule 1
PreClick ok time 17.697200059891
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.11339998245239
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
Dispatching rule Mount [map:1462,nosubmerged] Azure Drake
 - filters: Azure Drake
 - setting action to mount Azure Drake
 - found matching rule 1
PreClick ok time 16.862499952316
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)

Please do not modify anything below this line.

--- General ---

date: Tue Dec  6 20:01:20 2022
build: 10.0.2 | 46924 | Dec  1 2022 | 100002
version: 10.0.8
locale: enUS
current profile: Default

--- Player ---

name: Danessa-Thrall
class: ROGUE
level: 70
race: BloodElf
faction: Horde
spec: 1 259 Assassination

--- Location ---

map: Mechagon Island (1462)
mapPath: Mechagon Island (1462) -> Kul Tiras (876) -> Azeroth (947) -> Cosmic (946)
instance: Kul Tiras (1643)
zoneText: Mechagon
subZoneText: Rustbolt
IsFlyableArea(): true

--- Debugging Output ---

PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 5.7994999885559
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 349 mounts
 - trying Dragon Riding Mount
 - found 4 mounts.
 - PriorityRandom n=4, t=0.800, c=0.058
 - setting action to mount Highland Drake
PreClick ok time 24.655299901962
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event PLAYER_TALENT_UPDATE
Updating swim times due to MOUNT_JOURNAL_USABILITY_CHANGED.
Got refresh event MOUNT_JOURNAL_SEARCH_UPDATED
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
Dispatching rule Mount [map:1462,nosubmerged] Aerial Unit R-21/X
 - filters: Aerial Unit R-21/X
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 345 mounts
 - trying Flying Mount
 - found 142 mounts.
 - PriorityRandom n=142, t=0.993, c=0.432
 - setting action to mount Imperial Quilen
PreClick ok time 39.3140001297
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
Dispatching rule Mount [map:1462,nosubmerged] Aerial Unit R-21/X
 - filters: Aerial Unit R-21/X
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 345 mounts
 - trying Flying Mount
 - found 142 mounts.
 - PriorityRandom n=142, t=0.993, c=0.670
 - setting action to mount Shadowblade's Lethal Omen
PreClick ok time 34.685199975967
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 5 rules for button 1
Dispatching rule Mount [map:1462,nosubmerged] Aerial Unit R-21/X
 - filters: Aerial Unit R-21/X
 - no rules matched
Dispatching rule SmartMount
 - filters: 
 - filtered list contains 345 mounts
 - trying Flying Mount
 - found 142 mounts.
 - PriorityRandom n=142, t=0.993, c=0.364
 - setting action to mount Cindermane Charger
PreClick ok time 36.679499864578
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
 - setting action to in-combat action
PreClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
 - setting action to dismount
PreClick ok time 0.12089991569519
PostClick handler called on LM_B1 (inputButton=LeftButton, isDown=true)

--- Options DB ---

TZ1wZXXTY5Fm5bLtvYNmadgGb6nAjlBjlrROv2oXPoBXrKd5UL2DhMz31Y0vk(Bp9xFby1X0NI5Xuj2Q
koexA037gna4s3YpSCXLRgMXp)PHnt7wpC)fF19x8HvZdB2W9oT76138tJZ7xpTB555Lh4roU7Q5hZq)
LXnd7pm)Oa73SB43hEuqDXQ13nT7rmWZV73g29yG4xpF3UTtZpIr(2XpnmF8rb0xmSBC)()NoYVFCZt(
WQJ)(Wv)PJEE4tJJhw9ia8ZP(U7ZR)ThXqFZ6FFCZMXhXiPFBE9JH9)21)(021pIb(HvJ7MoWd8xg2DZ
W82H59REmCRhXW)WWVo840aF(aPwpUz9(hXy)EslyZ6hb7Ig7TZtxVEZ43pE3()elTfVy86HJB(tmUQ9
(G2t1UFatOAN)rRMAF)rdLAFpGTrTZhYCO27dyb8WDEIs)jd4b0ZR9(qQ21EFaT5t4X)bf4tiO)GoBTV
)e10hMKE4r8akJNsspG(xT7hqLR0j19nBM(4aRfU)42Tt7E(0XDhGc35T5G3LPFsAK9(MWYZtlp35Zzx
)YZ90V2695i9zNmwFd9ngHRVLgHJgDSPb96jq021G55OreACz6hEh9RUwhMxRopA5yO367OwJyAT9DrB
9IT5gmjSOTnkk1gs5oy1qlPl67zO59T9Ua(PowAeoAUHGRJ6UthCMxKyi2LuYl5sbUrACH(SIM(uBJxw
5CFcOigueGc93MBDei711c0zhaBoLkurmk8ec(rfue)lasg)AtkNzOs4vVxrbIi6JwRX2wMkjojyz9k2
g5H6B7srmoLn0gKraGfzsJ4PbWMdc71jOaW8OW8izyWlSgaxbZjooy)TofSrzAPEakGX(UUi0caZTlNZ
QSIhCszj9nXgHJrm6SX97b3hsRwF2NeUaMvppGCBmekdTvMVp34AX4GaG0fGYqRqejrSJb0wqHEG3aJO
g7eqqYrhZhyPTpbHL3RYfrZa61aYGz5Jbbeal5Lg9Kj12GS2oiVfzqMgJXRPz2RMgK4YlCyOf1BGig7D
YiCbsX3lOeenEHTqeLON1gJPStwoFm5vf0OletmGjLUOYHjuN0zedkq)jvrsy8aE52K8LRRlbIJT)iCZ
KmHCFJ2mdIEEnIDr26SrWmbeGoHMgRm32qMgQ9GN11GDFxi5ff722qBNxj5(CFwvCjq0js)yl7UGD6q2
EQwfXk9SXtMHrONDYaTTUyVQA6tEOgtto4kmqQvWGy)sE2Of)wFFiR(KiAcmGEWljSxe5KdUwrEbgCwD
lqARav6fbo7(IrJ2m)nZJtUoZJdj9HusP6O(zO3fvKVnMAe0m599k1XGd8nOm3rgf9clQVVJ9Fjgt9Ho
U5((mutfvDs(QUeiiee)eelSxPUCojZhKSAwr6WSbmRutOUNPFYepuzWjJOjgmyaDO1yNTSyX6koAux2
yj6ynWCQTJ9hr)gX1H5fRghdSLRWOAB6kQRSxjXbvqBguHQ)q4tqDJZmBSSrbnDcD0111wmxdGTZwObg
nebwiWMGE29TWj8Tjp0CzHxlhMc(G61iqXMmgyiYQ(umrX8IIlL44CGo7ylg0QRJTcyXj50pimn2SmYd
UnqkBrgeKfvuntOibSBjMbNGsaJ59b0P6p1IkaW6y9Y(udCmGH46y3hSYymZMrIp7(GRWFz)CnkimnrY
)K4YLCJ4AIQfCKSDudqVipLWJ(EzWKfCwvVC9nIGPteUqAW87eh7SrHCs0e8PCOtXdS2IYCiYrUdkGvX
vBlCxlS7ut0YuGIvgLvg9RoZtDXViGF08567ZQvqGzllLunIcJ3raievjkrOEH(zm20DjfAq1a8Stfrf
JqNG1keKEf5iF8oHFs0jN(JxWJSOlqPRGGRSpdiEu5qSX5K4ieheAXErQQARixbldbePUxLtKnJtPksf
Xj(RqCwrlL4MS7h4RHCjj(aXxyvXqip1rr0Ltb25dwmsnUx0Tr2vMoCc9XIWooYIxCsen(utKvxJcI3Q
ioblTvk)GOANal8ujjggdXsKBAHAaB9KjHOgpHYrSN5ISrrtwD2XGoyIaYYwCWadijWyBSNdJezbFtQ3
iBIusMVneUpPyfmdtm3IHTAfXSJCLjN0ix(qVAX2fv)RitVKxOaWMvcJrei96nROyL4XQykdkxLgFgUu
cajjUch9YjtnlmtxI8o3iGhS7GGaqFwt1Hwfj7ga)CUtCW7cnCY1ONqnGlXIBrCr2kTPvfo9wBqKdhj8
qd(Me4wnSRVOIeWzuJy0boTIpuAob1ue2xT8NGZeLzXmdMPW5MWAFCYDCqqW8PbRbzO8)tqLOtzwDkCP
C(e5nLNNWozuIc3cSeEnPiRncNGsZb4oOd2gVFPQqqQMoBpa(t2qbenjHfZRROW0jKpPehA8IYd5FbCn
bcTUgl5w2aRtehPkg3ROzsmGyfkhmpeVpnWaokYZqw4p0wA6qYu8Mli3fY0Aj3HTQBlSAqLlkWaRhCSr
XKcQaZ5i2PAwbny1vf9vwWnjRc2PkhbLtWgMZEbFiV9wQBuMniInNjaXPYcFazD7mdkcj4KcBewbRdIX
NLTZW6Mi0MO4aMCuezSHK6yZrBFZjntbZ7m5hsniTSSToN6tWR7Ibkz5sBrHfgZSgTxXzyEbLmegj6vT
FsZkRPctQM9QKMY7QvfjaHLbdSK3keBMgCm(aud5jakzPeSXAwYtNd9rskvjYLB4icQchN1myn9zmhio
tKEwXPsBRP8rP93QQdiskBYE4bkN0I172Fyy3LJ8(6DOMaBwV9QP5LN3SCX3mS)W48U7V47xV7MRM2Uh
iiT36flUCyEZ4H7V4Tt74XChszHM(RUC8Y5Pptt55RpmC14gAgqtyX7hpCeq6WebTH5HFF1WoGFeYJYG
qqAyCZ(dZtBbZLO5fF3WMn7V)IPRV)cuGRz0o5GBXpH6tiTFat8NhMVAChqTeT9LfVA3VoaQ7(lE30Au
VcsgtBgyXBh2C18WV9Bhjy(1ZtFAC((lE1(nd7UctLIISCX3oVE78W6n3FXlgVD6a73A5I3rdbLybucP
iV4S5BocOI8QxK)RU7V4SDedB1WgPYt3rJf0)QHBpGfzXLJ7O5pb5gP2YfKtq)VbmxmTp851BwFZQdmP
tlXIpD3QPnxb(d55zXhwF14(pnb233nm)rMvahyl(XDp5MjA(V)ijgV)I)zLEU)c3FbGIIbT47g3S561
ZJNkqGX7IpmSBa45RpU7MnJSkdefRNxV)AGtF7gA0Go9Ks0cIA2(rqnaV)UXHzPQvVF82bc4atDKXZIx
ndg)lMU8tGPISwqr3g3buMwaAzDn)1gAeZd3Grsi8OuCksOSz4Ypv7srxUZZhMNhoS(xjQOQ7sXvxydE
X0Xnmtja9MFLuh(800vNYr8mhjceAy(tRek4dRwF5NgbBVhS9xpnFKK1B2C6et)fwPpbLEsOmTfwlSKj
OAU)mnWXzYcrOh0hfsr67Ciwfzj5(fYYHFNWV9REQQ9(tJR3mEfu)NzmHN6pC8awD4kMChT45ZJ7pC9F
hE5GmM8A(LwkVA31hf(d1fm7o(X7U)I3S(6rypmTbILifdqWUNpTzZWT7LkaU448W2HVqH1HTcS4xGbW
MHzWZbDnU9wtdMjHxtYjAwJZ3oU7awyy1iYzEvE508hxFfzJc9LHlxruXZxTEZvcii2saSykj(LlEZ4n
SP7IvRVLrksCFy9LQP13rmZ3IIqoSEhcZblGnxDCGvUarD2MBgpS6jGio7scR2EhZ2Fy1oOA7nVplwnC
10NnVbizKfF)ryzUEEGBbE9oJWLRhUuu9)bYRdTopFylzcCJu833nnFa46ppndY7817)e5QdQx9EUkXx
nSJM9pte)xyU2ZkNzp8s9zHTan69SkBlBeVA94wYJXVrUmwJANF284ahj4lL)NDyA34wro0McOa)ZCfV
FlHARbntbuifSBhHb10UNr9mE5kWwwYLEboFwF4GQp)DKcY0Npfv7(lqnG0SwCyAE7(dthpa)PJFMJbq
zaqO7cuKDE(lwnnZ(wO4tloFCZHvdZhzx1WF7IdesqghBffW3rkzxHYO)8nd73du(ithOYil(W08nROq
nKDZhM(S5jI1)EXW2DIliANBlwSE8gv78hMVH8OVf6hokiim9j1y407hHf7hjxJ3XiNh((j6dYBGmNDf
5cHIxbBzuu4fV8NbVyg65Fl5lA9EOf9MXFf(N4y8qH5RNh(8MNCZGiD2bXdLNjyh3ECZLR(cC(LRN3tm
UFyhRhgqessvMS)GeHScgU8oz0F4oy3bNcNbkDM8q(oYr5iplQ1fK7Odh3kd(ftBxVJLRl5sMb2gHHFn
r0G)4reRV0Vp8yqbDHmfmHHdNAyVy8WbrmEeouAGD9xpC4Gz9)cC4qpXIn3rm)V5oTRZ(99RyvFpYnwS
Xo73pI4qC8BAbZK25BNU54tOrUtK(SJvuoaYX(4Wv7Ve8Y3V(6dSaeRocCV7u9kZv25tFA1rsa(dxFn5
9NcvaJJGWwpUL5wTvTiWEsyQtB)OAVnmFZOyR7Ho8lNNiFUCGZxs8uqYN4xSf82)rkfEwZX)pEqib74P
CnHRddlk3JoYK5xoU5jF7X5JFeudTD1fpNqEGlNtgoCojEu0ZfVCANMs0lhh2CawIjiqrEB7Fc87Y0Cc
A6NTJwGJ7TaqFnLwglK)Wkk4neaOCEfoT6QKCnyUkF)KQv8wM7uDnK)lCLcKiSBNaH(sKDa7DMbjfGFC
3Q1GziEwyhCzfWAAfI6Z480HvCK3(VqnH1Eiecf2BX5KtTvKPgRC3q6zCoeZtipIxsEpUc(KYGrY(3)Q
3biCskR0MQ6XrEnapKF)oeR(VZJ(dLOlLpzlY8RHhXzi7ZptC9R4F9B5Sr5p)xpooU7j7ry2D7hN)1bI
VJfTjQA(wcOWsA9M7uN6NEcV8X7Ahjh95w4s8DicW6dR1C2rPXXEwapqQLVBzTG5lTJabn2K4nrDAztw
w3CYsBVE2qLgPWinTYqP9X2PBdTp303Q93OLzIhzOSOADjAP9jlJ0tBXPtRDez)PRppGqTvzSU(yVxgB
mg6lavqpsc4vCUu32Yo4ecbfYqXjD6r5CdwYvnVxNnTtwHIWUNuAJ2yAiuhz2OyxJoaTAO4ZGxRoEPKb
lRviKGAizCm7aQwwokkz(2Ez1cBy9RCKGR3laiOSUGkI77Ts)yhA3YtlMtBWZBheZWNsQyNKF6kBh2yz
FJ0xuoToPTquxSuJ(tfQEFRkc6YEVQSGdHWxATvMIEMxwJUcQKkuEVR2VV2Q8PwSBhV3yfMwDfW)A7co
tEMJkwPhsg6xpoABw(cvlavR(KtQxIkUJbtbLiZg1wa7hxwEu8uJrkf6cFMBI6HccyQgnYH4aarsDvzi
0B2KP2OY70dygdeLoTiqvHUEqXA3kAukrjgzNc8sz4wwkpZs7SJDIDqwTidewwjDZHqORRsLkE4BC(QI
QA(qwPEvNL)mwhGGQDPE9NYAZNxcgsUVnQdrkelwntHiwCEfcMhlWi8gH6uOGJvURqOYxXw5aOf(G5eu
RtSsOfERPKZhKMstEZoMBmzuxVkfjpxQhd703CLkCQlFvmfJL50xO2QukwfYcVvpUoMj2zoa5ddju)Sa
tBO2HLSSCAc0NPqU4317uUyFY0C0tFfZPw5yatNmh9eoTPl4SEfpuYuPdCUYUcIOuSDepwRP6y91wnlv
T6UWvvqDNQhPGJd1ufTk2NlE8CzYREzkDfrFoKcfcvnb0sOjKxN5NklN2jMviKufcC2pTLfvie9uJDsv
dL2iJjxNYWjp1MHENCwxlpTCTOYMYC6QHe1IhIwXPR7kuCQS4(YcPSoEK2PyKlMIuJMscz(P26OcQPcF
Wmv7A1406PpyJ0I4789fBTunICRP7Oxeafbfub3zG(6inMNDGU8zIvXFlpae6sjA5aTSgRm6k9PQb6Xa
AJuvi7Zv(OX9CMkMEHga8HMHnBiNkmhzDinll2lbCFJnYgLp1fmEp3VZ4yDNi77QyN5ZcvZtPopHlvAQ
8zxjGHRgzeJ18)1e0KoAj7bfVT7HHWQ6SibYflbFM7SJuoGJxsMpPkz5)G(RKRg8N)SeDZu)j)fElThk
)RyjNVOXLW5xRwQElvlYZyn2ERQlDYjDdZI(A)XA)k3OA)YdqTFPW4n6s1fmpr61AXMvS(Pml74zqqGg
1DUJCn3uaFYx)SeTZCuyhnbYDjQiYjxzbEsX6NMim5s1g7lisf76ozsQ6AYCuHgv(h4uMdtxOeJIl3kt
jPCXtxWN1yK2nfdqn7Yw63KsEtDwD1H2vqWuTrbbjlSM60d1UpzKw632C0tRJzeuqot8w8ER3WlDjnfb
FsjpsGBbbX0RlKLfOETXqRixixDS6cO3abBAYaS7JLJ9BKRJmxhzrtWm7auTS)A7R6KbttcZYstnNRsv
7iNza40wX9uSonfyrYptvwOwJokcvURcStycNSe2wtmra4XNqnwypYS5K5xm8cotXW1Mpbd0OibkTIqf
c91w7QFAzpsX2SmLCQSN7xvOjFxDveZ4h69NbFQ3EghNQMrI61m1MLb2(smr9ULQlBL1QbISlKLdhUR)
eEGjhPnbRUp17hKcjZHLfkWotzUr5IaGwTB3cJj2v(PTPZ4f29AZGqS(PzO34lBPnhnhH6n5YgBvtUS7
8YUcHNS6kyB6fbMSCRA6AQmgnxd7QNHflg1uzSRPgAmLJfbE0vTG1vnrstTnYM3sBG8P0KktY2msts3b
njyTujOmvmMLZ0X0ZgMxh58n5(tMNsGOXkI2BF67RyNY2jlkRF9MmYGsVENGtixqc6tAtSwgV(AcP0QA
(3joLUaW0XURhDj1Pn02Z15RQW6TQtMEUYic1Wpk4jVRwGisxXvOVORc0CDaEduEZ9cMLVoaTvs(x2eK
EJu1bem0oFsJDLzDIF18jiwSsn91wtvc7eG1xOmxTrBNDotdK2B0jOvSUwkLFYT2Hxabf17(l6pf7R57
gSsfqT2xibRUs69bf0nzYMQWVyqgvvViTv(yT)(kK6Q8flYVC)ZzeqVAFkSY1bKQFwmJTuNSlyMRExPa
g66ljr4d15OSLCF1CoQk86vx3WVUcGozj1(P9M3uqjZFJE)CrRH2OApy3XZLsrvkHkcTP6SS09mbmpFL
vrk5QOkuRlzIp(Xc1xmDCXktl5RlBxDAvwzY2DrFJzYO3VFBavpAknOxfuBONSyk10LpjgOvVjOeyr3B
i3xXY0uUODfD1(vumfTeXW1l3INMAsL0VCXsQg61erNMfJlMkEaPTzufz9H6y1PHHAOlUMC1XAXPBAu1
F7k6WT2NmEoMMowV)K(pfDTOFTw1Dqfxuui0BXXl3BSL6BGatxF5eYNTwDXSNEHcFH1P30qWzBBncKKC
vvEnklU05LKLBSez6kf8HuESIPrXDsNSMN0Qb1GMSnbsBJ1u0CvLLhzOGjMkDYYCWU(7llVLaRFbOD9r
R(445mORzFUjyAXDn22z7SsDWZ)KzPevFtY2na9zBbbSyTH(yTmxgwHurvXFBjtYYJwyjFrrlPi3Byaz
Eg6lPkwQSro7mtz9YgZalBxku9QS54DB5nMv22ncXmTnXQ32mLaARWuLLPoZPvBWzSy9Il6wkxIpNcu9
AnV0Ue7OD9M25ynvlfg9EMYaTSDoSBeNVc126a6luD1xOjIS7(Rmu17sxx5WmAX9YvNFOeaIMvS2O2pP
J0w4p18ml3lCc891wtLwlH6KxRc(0U3ZqDSZKv2vutq7UYg69LD5Nc16vBxBypFdevIj2yfhOPwxEu0y
TXItzmY(A)2KYvNnwDljL8EterBT12gzOuYicuMggg6jT6lWYQaBSluBZcG0h6ozswqb5LzyJvvmPTiz
(4OfngRdiwb2jlHzgLJLt1HYk1scOSPDCbffgZjpKKuWYtRX1usOQX2ECrhakUM3wkQOzKQVmo8PEzjX
N21FCjY0nzz3Hp7QFAPk3AvYH087mVd2JncJLSI1fM2vUTHp7sMUSCZAvUHQhA3EC72bdQUnw0g0hOZY
YDGeasEUpatsnw50lVCmz(2Q3vovSo(YuXdT1QOnVRGyb9T8XSluRIOkaW1fwbGE751b0u9PQllYZ0uY
BTsObrOaQmL7PtXQgtSaozSoNQJ8MQJEvRH(VgZpCSOUQxYB3sX9TIF2lVGjwJdsB1Y2SbOkTF9rK5ed
6wtjpB7gIDKBEsBTdQOClPxkNVMPAALRfFvZfPCwZn2sPVzhhFKhA6hOUILJFiz5uhcwnOX2g1CDWTN2
SYbTOgo5EBt(o78iHtOIdzB2DTf8ejVxA1cEyxhAmg9oTZus2QxauamhT2L8FPKbMtx2MwdcLdTrVV14
RUSTpIGfZ2EPoGNq66wkn5yPkjKXO5xjuQfQ(0iyMsRTtjYvt54ziOgkONDsLKFlROpXUYgf0hfcgq2o
ql9ThcSsE1wgqprRxMo2HSZWeZhv5Hhk5)uDCvdxyhbjTLnlXAW(oXyxTa0NDhMM8SHD4CSS9wP3ABM6
ZLtFnA5uzVVbfK2Agc1OWLkDg(cPRT5i7necEsFBTEtbRkub7Kfymv6hgDLrgvjHETYDQLQLtA2mW5Zu
Z8fvctBpli8p9v7IbGxAH5ToL7l7zYix7XU4eUD7jjRwS7kv(H0vLvGb1jA4H66w3)QQd4P9PAB6cOBQ
cwZYXoXMtEXBm22xhArHiEYMjm30rZ0OTEYK277CjBKxZeXk9sRVKjI(iOXN6dbGPlVHQ6JrsAmOyT(y
uS13PlAPotq5Yxns6R4NX3ATANPVpiMxzQ(avTacWDNsaqHlvMK56sFJSkVwO)KZskc7aZsany1UIbQc
jerxfB2diw0xZvGAPGBhoV9QsuYZ0GKxth(N(eF4vTCa3WDUMEMZo8r7nPYtQKhct)QAffUv9hAVdkYD
sJvkdYcXueCv9VEl5SYlruHPfxPRwEaZYV1o2NYPoPVkfUZCYoEAFtztxWvR5vQ1SLHTQTvYESfnT1IY
R9KKDchv4iW)PzRRpMXLsHsu0l0A6X4cvB1SP1odc7DhTucVy5LPV3nLcm2y5afj5XjfcQ1mKL34l(e7
Wurax7P1l9KBJIPrQ)1tyPSvTwfbZAYq6d1MNE58hawzbJ1h7RtuUvXh2lQUsYFvhyc0B7qgNEAjcJDA
66t6fGVp3zn2ziQ9KfDq5PMyoF9I5prsf9vmvff6Flfy43A3YfU6Gke6cnMjJ(8S5X6TALzpbmLSSS8S
N(9s7vKHzHdbYubSap2ZAwuvnSI0bDvC9KeWuUs0c2qjtAEjKx5gwhI5RB5uFERmHuofe9jNzGu1jAk7
aafhmzuKDWX13bl76Wxh6jmvbNOnsBPIQ)1WWgQfwmusMp3zE2dLIhHcjjRzJLiZPVLsKEBzZmLsctEt
k30ecPnPxVHQ2B1YX3WktI03vcW7KNOlp0UoBZoD(2sYIedWC5Y3iFPv5rdZTglocdw0ESzaDdqPMYb(
xUjJTLYFR)XarbzxXFTL(dLYUVWFY1eCurAFjgtcjNlF2wR(vtj2VtFu(cqT4PeZ30JCwznlpGmbN6RH
lTnhKTS3T)mGWSSYLkLpGefa4YuA(rCLl5G(ax5XwUDFKa0s1Qp2wkeOD5gPTxyr51hNmAejIRAfKhjJ
Rj)DkHNU8MmXNnUYnyaM)wUjD21jbBRnygan21Ef1SsMvYYuV(kQT)WYOCnludo5pJR1w2kDt5cOIJ0W
cfvoSk9p)nOrkGyP2nnzBtt4YBQBWm1vUciE9icpSCX8Xn2J2tE5E8ZL4(l(p2oC7ZOCy8pD30(JFC74
8nJx93U)IZgNxJ3MYpUBnnQ3)vE3)Y)gToF58OuRE6PtA7HN5LxV(xcEYl6tVEZDdFCZ4t)pV(YNrb3J
rD88FreQJ3EGHpJInQJqEzPLrm(BhMhEgsvjL(7q61x9mCjrXRa5pHk)F9u2d(Qm)4XdhM2D2L4PCyVm
Z3mo8RJ)04Q1xUz8(x)I173QRYUj82WwV7M)29V(5t3E3hWtz4WEbjE9z3E7M7EpuwU)1Vz921mLoD1Z
g2C4uuYiAc1E)pE(tV))6LV5F)F8eUIFmvZRV6lM2lE)zF7pC(7F1lE15F7FC(NYb(Qf)8RE79VEX2H5
dkU(QxsJTsm4vb(pD)fl4NG0lPMFk)0jwFy4Wi95VG7z)l5ho5tX7vC9vO1xUz4wzQlUDepzoYQIAgVV
m8dC26T4duuKe(iIi6LfJFec3vFQyVBZXTaSVF6YRX7eGFrN45zkpl2dJYm)r8i6WLIXNfG37Cfy(Mb8
wFMh3pH33Wvfj34Vcky913FHsZYmkI2x)nN)I7F9BhUCE6(xZA0))6a)FBDGd6)V8)o

**Comment by mbattersby** [comment] 2022-12-07 06:36
This is definitely a bug, something is getting confused by the slash in the name and thinking "Aerial Unit R-21" and "X" are separate mounts.

**Comment by mbattersby** [comment] 2022-12-07 23:18
This is going to be hard to fix, sorry. It's caused by a lazy hack I did to support using / to separate groups and allow you to select from multiple groups in the advanced actions. Unintended consequence is that LiteMount can't activate a mount with a / in the name from a rule.

As a work-around for now I suggest making a group MECHAGON with just that mount in it, and having your rule use the group. I believe that should work.

**Comment by mbattersby** [comment] 2022-12-07 23:21
Also, many many thanks for posting the debug info and letting me know about this. It's a serious problem I would never have noticed on my own. Thanks!

**Comment by mbattersby** [comment] 2024-02-11 12:21
This is still a bug and I still haven't fixed it.

**Comment by mbattersby** [comment] 2024-03-08 04:44
This is (finally) fixed in 10.2.5-9beta1 and onward. Closing

**Closed by mbattersby** 2024-03-08 04:44 UTC
Labels: bug, replied
