### ISSUE TITLE
Rules deleted

### ISSUE THREAD

**Issue by elrenno** [xod-wow/LiteMount#185] opened 2023-12-05 00:50 UTC
What happens?
**When I initially installed this addon, each keybinding had 3 rules associated with it.  I added a couple rules for my own use.  The next time I logged into the game, ALL rules were gone.  All completely deleted.**

What did you expect to happen instead?
**I expected all of the rules to remain and not be deleted.**

Did it work in a previous version of LiteMount? If so, what was the last version that worked?
**This is the first version I have ever used.**

Please do not modify anything below this line.

--- General ---

date: Mon Dec  4 18:38:58 2023
expansion: Dragonflight
build: 10.2.0 | 52301 | Nov 22 2023 | 100200 |  |  
version: 10.2.0-6
locale: enUS
current profile: Default

--- Player ---

name: Lônesome-Area52
class: HUNTER
level: 70
race: Tauren
faction: Horde
spec: 1 253 0

--- Location ---

map: Valdrakken (2112)
mapPath: Valdrakken (2112) -> Thaldraszus (2025) -> Dragon Isles (1978) -> Azeroth (947) -> Cosmic (946)
instance: Dragon Isles (2444)
zoneText: Valdrakken
subZoneText: 
IsFlyableArea(): true

--- Debugging Output ---

 - default combat action
 - default combat action
Got refresh event ACHIEVEMENT_EARNED
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event BAG_UPDATE_DELAYED
 - default combat action
 - default combat action
 - default combat action
 - default combat action
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
 - default combat action
 - default combat action
 - default combat action
 - default combat action
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
Got refresh event BAG_UPDATE_DELAYED
 - default combat action
 - default combat action
 - default combat action
 - default combat action
Got refresh event BAG_UPDATE_DELAYED
 - default combat action
 - default combat action
 - default combat action
 - default combat action
 - default combat action
 - default combat action
 - default combat action
 - default combat action
 - default combat action
 - default combat action
 - default combat action
 - default combat action
Encounter started: 2737 (Volcoross)
 - default combat action
 - default combat action
 - default combat action
 - default combat action
Got refresh event BAG_UPDATE_DELAYED
 - default combat action
 - default combat action
 - default combat action
 - default combat action
Encounter started: 2731 (Larodar, Keeper of the Flame)
 - default combat action
 - default combat action
 - default combat action
 - default combat action
Got refresh event BAG_UPDATE_DELAYED
Encounter started: 2731 (Larodar, Keeper of the Flame)
 - default combat action
 - default combat action
 - default combat action
 - default combat action
Got refresh event BAG_UPDATE_DELAYED
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event BAG_UPDATE_DELAYED
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event PLAYER_TALENT_UPDATE
Got refresh event BAG_UPDATE_DELAYED
PreClick handler called on LM_B2 (inputButton=LeftButton, isDown=true)
Refreshing status of all mounts.
Dispatching rule LeaveVehicle
Dispatching rule Dismount [nofalling]
Dispatching rule CopyTargetsMount
Dispatching rule ApplyRules
 - checking 1 rules for button 2
Dispatching rule LimitExclude [dragonridable] DRAGONRIDING
 - new filter: -DRAGONRIDING
 - no rules matched
Dispatching flow control action IF [mod:shift]
 - IF test is false
Dispatching flow control action     IF [submerged]
 - IF test is false
Dispatching flow control action     ELSEIF [dragonridable]
 - ELSEIF test is true
Dispatching flow control action     ELSEIF [flyable]
 - ELSEIF test is false
Dispatching flow control action     ELSEIF [floating]
 - ELSEIF test is false
Dispatching flow control action     END
Dispatching flow control action END
Dispatching rule SmartMount
 - filters: -DRAGONRIDING
 - filtered list contains 311 mounts
 - trying Dragon Riding Mount
 - found 0 mounts.
 - trying Flying Mount
 - found 138 mounts.
 - WeightedRandom n=138, t=8.570, c=3.075, w=0.333, p=0.039
 - setting action to mount Geosynchronous World Spinner
PreClick ok time 225.91179990768
PostClick handler called on LM_B2 (inputButton=LeftButton, isDown=true)
Got refresh event BAG_UPDATE_DELAYED

--- Options DB ---

vV12o21rU1pN8IdqD)IEZoAWed70jWDqEjihOJvFKCJ0xCoDlGzYd6RA(dMFSSyvCrUJJDSaYtXcqA7A
ZIflw8YIS2NtXt)ZNU99)05RY)E7R)1)Y1h)XRxo)VF56NF3F7NF3xJN)87QPfvp)0hU)J)lxU(Y9p)0
PBMNE90TFZ57F48lVE98)55Vi6)()6F5PlV88Jx(IO(RVE(L7F6lI0V58tqMF5XZV(LX6V55pE(6RV(L
qlO(Jp88pE(b59V8PhF85N(7E(tp96l4))MCBmMTt3KoDtmxlXb(3t3uIPWqESkueM1YA4zVmZRNIL0m
gwpIzLBrDA9HmnWSskeM9nTPupShfR2miewfMvdCAvDDtHyyUjTft59cKWuYP1JyWzzZjilHMY)wnm03
xk7fTpGGM6YM))Hk527F6Lxp)07VS0aXt3(DNF4(hV75RNUjC62)aShUCfNAF39p9X7E(XxaFQLbEXJx
UE(H7(87El03pUgf86RF8(R3HZ5xU)HV6ZV71F6I(()Mx(87(7F(NVa6kLYPBF71ZF8zW1V9LhW6Uov(
5Rp)H7F4Y3D5p)YVJ17TV9Yho)Ph(FZG1j53Wg1j4xZS84k8ByjEGKFnJp71(oBTT4W4XhfZU)PR3)81
7F9Ev73YHurphlT6CBreg5OAPjeu3wAZCunPc9AKN(HrkPgkLOyZjN85uz6KUNvgMmMHuPUn(sWICK13
hIvNYITOBJRimZBBktTwOUhnhBDD9xeu8r30spbHMrBKul1wzy8FlP5wozUmLcnPN55wOkXYCS30y7vd
MKQCQTCKxBPrDOmQxuFZXiN1DComkfNYj1dr1FmvZr13kvWF8bvrUnnTxjn6BEnkDoO6WM1hZoP6ojpt
DNuvLHGpPndkQUnnB9Xqf)oJrG9(MSyBoRjDYPCwzEQ3vtdiL6Il6HKPhQRtJAeH52tPXWEJqxFSh0)v
xGukRht1zkP2wJAGcagvJxnZ5uZhmAsv30dJO)(Kp6wNvNDnkBgMeAmqeJL7AjmnpONnvQeTIAfMMtQQ
KzLmfGYuC6PkOwBu0NcXOAs0k00g74G6fHTFzljn4Ks1Bk0v17m0MbJNQ7wRhuLdms1xNGLrqDYh0XUN
BQgfMM8ei1RJSDKRwgTYKQr8AvKsDOC1hZvL7Dt3jBDnctOpNUePU1LHPpGwGrvk1QVHnXa6M9JLe92G
REsTRxp2Cc2sAv3q1(ETBqYuUmhqjTFjo03p1OHsBhousMwyGprtK4ovtaNQ1MgIq2QvBrA(R1D1mhcD
BR67QOBeRYVCGFyWo3Fd9ifba1qmR3VzfsP3clByz59ZPwZMZW2TttomlynIjqKqRLsLHrtDe0Py7ngf
1SRKx39jPgwLPf8ofvD4OtdhztQCFgy8fHNX9CGNuo5tFlNZrk4YHzofPTAn30qUImPBDKAO0pmA3Pn5
JsfrprDBHGCYLoDWIhoJ1nY0IogNiFqZf)QXDnmTSNvVHzGotG0kdKnRnMDaGPulJimuZ2IU3iWQPYyQ
DzS0wruvDpcSBU)rE2G3wuzcwtQgbYK6av9STs6cMInXulYMVBYHZEvlUOClN150CqXG6oQdNs9id5Yv
turLqhyKLRA7PItjbtetdZ)R7j7Z0IswlZnxnUaOzBNakPECkA00EohKFcXqY4PB6sNPULbDDUV)ulcy
UP4lwuQMPJPRhP2lsRnr40nNyKWzlNtMYzxFamYywBW8uGugu9uTqD)69rQXQebb4z1LoghlclBD3LGS
47j7XQLrj6zrfAzmXqrrUKHRHk3cyjDuSyoAP4C)EPOd67xZkUQIuoKtzZFVVXPlL8OLiK(eiEsIOOaY
UdNLmxfK7H6(MiYne30reKfRQSsz7KIMLWglgYj51QAX9PxZVVMec5u1SvnuI20N1WNvZFSBQfDsHGgR
pI42bJ9kGiaOPKDV2(2wgjnyCeXPwFCuMe8r1pIR(jyQh7(GdtsCXREysQHBNrVKbv9NOPyuuuliZGHy
3mb50c)5LWgr0tTieKWysm(WCp4ZQ6KwnbS7dUfq4Rf8Px8xRQ3eo0I(OdFunSWKCcoM0fb)htMNSa9Y
0NMGONPvSM7jb7aM5uMUlOerzDeA62taqfDA1fazHN(APrGIabH6SG4ktNYPtPHBGULcxj8X8Wnvl0at
MfH8cm9nNaFlOEy5kqxN9PPmRH4qS2nKOV5eONBiV2S689G(4WQXsH4bJOUpSX8ZqdHa8XoWQHXkgBPf
Zt3YHWfkaIsX5Wy5WUg1PLzuKrzcDKCu9(I9LfzsWRev7KfPQlbIdwDjN6oHavgNLeb8GsWA(GhMfz7y
LFnTjirC(XKFmOj1eRJ5M0EnDqZWZCuRUgkgYNysPBan9CIPvwZPEsJdwOF2iq0dqs6uDhQuTKr21QBt
vCZaj8MSbQHKvU9S1ie5XG8THCXhKb3bW6NGvMQex0xmpftYY2JuFeixOgC1LIMre3gl7QP4MG3y0GRm
BSMBuhVhdqfa59kgbalPrKjiyvOBZsp7rTpAL(4L1kJXhPzgWfr1zK2MWPN1DiThGLO1z0yrOBUqp4JP
HlP6bd8p133IgWmCwu25nI9ApOyztSM4fN62IYuiqPP8x840nfayYYRIw55Y89fvTHaGew1kujfpfNYE
eaNj7GX0w5b1O1zgWZP)(e5usoEdIN5mtBjHanoaSeO)4mMjYSDpotNo2ytzsvBshcrpPyHjXS5S6O1S
6(UQ4JYS9T2HTLAjizowozWXCe9j1yrvPcbMiLICqTTLqbSIoREB4iRzBILrh2oGnhdbI1gUGYjRDN)M
7AJWbGhQcmP1M67lcC(MpRHZFZdkrbaq3QCAwcp4yoTgKHfB60Yq8O0NdJArbSydHuwLbz3qihPA0pzk
uAdeCiCgZfNvAOCCiKD5wDmhXXHfvFpcEhmHIXUGXGvTO0crkuwhramSSV((2wHXm7zVRRT0bwPAt4AO
NXfRbTR5RhxIQWC4InxTPifxsq1Nw3jqpKK46rNGHX3QB7OBhzJf1qgrRRrcViBzvtY7vSoIzcXxeqiV
MnlvFIWuJM)ELv9gbiMI5SvQFOBWcJndSd4v2NgZC26wute3Xp8gfNwDAcPh4RB)QLlGuib1Tjcfgdcv
gDQYZieHsBkD49hfxnYIu9Qgya1PsWkviLS0FRR7igVzEAzgs9SIDBnj)0vTV0BkkVnQ0d3EMn1xoLY(
CuuWsFYBC57oATGs7Ivhevn1uozmaVNPtrwSKpA1NLg5PYLf7jngheEMzcylul9fNuMcRa2p0kRUox6e
sJWZPrjpTL3V5FD049lGJk6upMHc9dQbY1dxVLqqXNMURhiLZ0EmBsaBodamZSK4bEVEa0OgbkjGRvnq
2aeViWLrADdalg()bB6eulMf906QZCg1UwUinQ8Aw14zDrC3cBG38d0QS(lOUzb8reFGhXrlcIWu1gOx
zKXCjsvVW)XA9LBTJOJq2dAoBT3smI5Dy2YeDvfOtuHgzFBe4zI(0lUMDc2RfoSOPVSaQUiZQEYymw2n
MKwSvTAxxe01QLfEWYoIz18b13dROSPQO78Kh2l2p8r1Jve4301aOidRUVyw5Xm8Nv2kDay6tR5pEGz6
sGazwrpTQ15JK1oKoRXdUeXif3UvJhGAWUOe8R9q6(UoOLKqOC4VNtA6r)ydGHl3GhSLsYkYEWavl7jf
cwX69gwaZ5Px1JJv67SZ2DXnj52MSJUcHljhICATPUfaWpEFn4XS15ARpvj21nb1X4axt(OmtkaEDqAR
gbSNkHbBl)kzpdCJIQtoFjWejG7MwueRD7zwQ0euhTdzf9C8erLED)KVULcJXiYBXgn5hVn3uYAYZKjt
tZo7xmcIZOCPk7Yzgr(0SdPiot3SfzX4flPF9cs2hyZruHiCLAHRFLbsckyZs73mTeXHB2prykV8i6WK
SR4AWMGGrTUP7oMcSFL)sT16wfrBy2xWQ62MklTpvjaqNyhFL0peyrHDPlcNjIeDAGfIOWd2gPkdhb)6
U2YZvyC(i8a2cUGbV5KQcUC5BgmOXbjGx1LqRQUszRrNi4pDsbewIKRmYtZyoyTWiZoPbmveynEKaRX5
zKYamzi032KpgLd)ijyQqxGvDxviibrKLC0hCNfQSma50l7sRQfKUKRCfrjyKSCY6XX(ZKjVKW5r26(y
0nUjFtbkVKm26O9MvcAMTMe16mnoa7B6aqpOjQQISkWdFrZALcL1k4x5GhUaSxkPh00uFYg2i3lRAsi1
4UTiQJjXYk1kQVUy3hIWt7iAs3lyGxSt2zYqhAyIgcsM9JYD3U3lRYxg2Ijk(8kQBILxGdzc9Eut86Yq
CkI6mz9vdMKdn3P0(3ShTxxIKurVYbuQfV(Fz10iwWwMswmZ0ZsIyhcAXlbIo0WFxnWrvlwMEjHwA1ua
iGgMdR5Ki4yIEqbRzAtaPiQSkKzNqSBeLxuakeJnftWIpCwU5dkwwBseoTB2hiZ(cAtlyowxfHiXWzn2
Kiel2U6tW0I)OATgnapOS7bBnGyeOj4GtOQDG56MvqsiIrSsSFgsLrQOkT(qnrQw)fx0UjijME91gqcY
QApe5MvOpZ8QWBD7Uxf8V0gCuO7gmaAAGxEt9lZD6ozPLr9Ie3oCXcu(a2rD)J9mXXbbCUvWR72LO)SR
rfOruPACOVWfQPk8(5wcQcOTmSgIBvLixtGgcqsHOOsGrOI2cBjdFIJStAQGfqDgiSgWlLGLd0MTPG9D
hLTg9lrRuzr6)QjRREBkRmOmQcqiDibexv5dsHB1KHXd2V7zHiJ86pwCTQ2Q88xAqdVNDrwhoP7z1HJO
cdjejMhO(jaT8kDFyFOVjuIRoDwQ70CAHgqmpqIsMAaGUAhuRBHsIoO(xcUsvvMTVFcmf6kwgt3MsDkK
w9WYCYE7Gt0Prmu3M8i7AzMmrL6Ku3(QuK6BPTYW(UYKYuAoB1J9jDALoeWehLvdzZkxjC6KdOlzniYA
7GqPURcOuxnuH0DgvaRSvcRL)Wgu32YxiIg0iqLkqof4nulaf2Kk5W8ZkgtfzBz)cLIeM2J8yXcvaCxm
wNyQQoLc8y3bGXho8XHKtrB)ZMhLS(XkxKmp)rqvZ)jy1PIuRBAhD77vb(QSTlzRH5Rfvpl6Ps)aB3sT
eavd1kk4IX1TwRhzHpRsSunHyaA(68tcjkaTuvbcqMy6fwAyKbysaKV35xt7K5XxHnkjMxOoezwUhhRS
SXWsZYMIU6HVA(Nx1cMxF)awJ7TRLt27wR)4hd4cz4WudSNQY37sz7PKT7XkW8mZe)Yue3qMpyYRcrSs
nldZne7jIygh46XHGeA4cQoRATBD7OyxLO00B1IqsNRN4qnB3zxIn1TJnOQNXbgFVKDup88VtfPstXox
I6YUniFIrm5uMfki3Ml9it2fuUG2OIIuFbl9RBFCzbB0mu)A)kayA1rw65DNJXLso(vDrWAKg0Qwraf2
1GQ9nTU(GFyAKiRMeEKJXo67su1nyvo4CANghOpxNvIlDj2IEQg8s4GIlP0sRt3qjnP15Ni9JxaKvLIK
YF60Q2VLgB7Gap1GKyTHgBaATjTCtzWKFiDReHQ8lFKze3U9r3ljQtB)QvrgC0urnXrXOesA2UAh5ZkU
ABXeDbyzLRmX6QoysVLv1UYM1NtNbkHffMTwXkEdSWNkbLWFlbX138OkNDPCP1JYLnvO6XAtr2c4vN8J
KzvYz1uuQiJQxz7tbmb(ECu1Boxh22Jqgf2g1DAZkAOZWwllahZN5bzxvd)nlK2k1M9E1AUpOtlrXaFI
or(vODsSe4NKUKLtvEijojvkkuT5IM7L(JKiV2hS9f4)cotRB8MR7aHNt8BvwGMOBiuqq4qitMLQZpcp
jOLgswYYUE61t3E9tpWFMe7FReYIDRir4VkYFvXF9Qm6(9F)9pE)R)H)07F4t3D5ZV7F9U1p7HR3F35F
8Hl)BF(DV9h(6)4)4n)W3(2V9M)4VkRUPT4hw6NF4UF4xU6)cU)Hh(ZcF)QNE(3DD(hKF7bykpE(NFdW
29vV8PF8Xlx)4L7aXp(6Bs7py9)BKHk9RFfxI)Jp8(3GtLwtPx8olo98NuYBqqcLcXQR6uC5p961ZVra
a17qGpU(3F3BKpj8)pOf))f7UFTFloVU(ZP)Rd

**Comment by mbattersby** [comment] 2023-12-05 05:20
I'm not aware of anything that would cause that. If LiteMount were losing people's settings or rules I would definitely have heard about it.

Is it possible your game crashed or you force quit it, causing it to not save the addon settings?

**Comment by elrenno** [comment] 2023-12-05 12:37
No. No crash or force quit. I wonder if I might need to just reinstall. Sent from my iPhoneOn Dec 4, 2023, at 11:20 PM, mbattersby ***@***.***> wrote:﻿
I'm not aware of anything that would cause that. If LiteMount were losing people's settings or rules I would definitely have heard about it.
Is it possible your game crashed or you force quit it, causing it to not save the addon settings?

**Comment by mbattersby** [comment] 2023-12-05 22:24
OK thanks for the information, perhaps there is something on first run that is wrong. Or maybe it is just a coincidence an something else happened. I'll check into it

You should be ok to just recreate your rules and they should persist. If there  is an error with LiteMount it could only be on first install, as far as I can imagine. If it happens again or if it turns out to be some other problem that's affecting more addons too, please let me know.

**Comment by elrenno** [comment] 2023-12-05 22:34
Not a problem.  I was just concerned about the rules that were already in there when I installed it.  At any rate, I got what I wanted put back in.  Thanks for looking into this.
Mark Renn
1517 Fairlawn Ct.Jefferson City, MO 65109cell:     (573) 418-6830home: (573) 556-0525
***@***.*** 

    On Tuesday, December 5, 2023 at 04:24:54 PM CST, mbattersby ***@***.***> wrote:  
 
 


OK thanks for the information, perhaps there is something on first run that is wrong. Or maybe it is just a coincidence an something else happened. I'll check into it

You should be ok to just recreate your rules and they should persist. If there is an error with LiteMount it could only be on first install, as far as I can imagine. If it happens again or if it turns out to be some other problem that's affecting more addons too, please let me know.

**Comment by mbattersby** [comment] 2023-12-18 04:15
This is still on my list to look at, but unfortunately all the hoohah with Tindral Sageswift has taken up my development time.

**Comment by mbattersby** [comment] 2024-01-16 06:23
There is definitely a bug here, I can reproduce it by deleting savedvariables. Oh my god.

**Comment by mbattersby** [comment] 2024-01-18 12:20
This should be fixed from 10.2.5-1 onwards.

Thank you so much for logging this, you have uncovered and allowed me to fix a serious but I would not have noticed.

**Closed by mbattersby** 2024-01-18 12:20 UTC

**Comment by mbattersby** [comment] 2024-02-16 07:28
I forgot to say (actually I remembered to say but I posted it on the wrong issue because I am a doofus)...

Many many thanks for posting the debug info and letting me know about this. It's a serious problem I would never have noticed on my own. Thanks!
