### ISSUE TITLE
xmog: Conditional seems to be broken

### ISSUE THREAD

**Issue by Sherlockell** [xod-wow/LiteMount#163] opened 2023-08-27 15:19 UTC
Following up here with a bug report as per our recent conversation on Reddit; 

I'm configuring Litemount so that when I switch to a transmog gear set, Litemount will change the mount group with it. I looked in advanced and saw that I could do it with xmog:outfitname but when I'm switching gear set the rule that sits above the other takes precedence. 

Heres a screenshot of how I have it set up (the rules in question being 7 and 8);
![image](https://github.com/xod-wow/LiteMount/assets/95516063/30e7d86a-d6f0-4876-8287-7e0d88cc1892)

I want the black group to apply ONLY if i'm wearing the 'Blue Reaper' mog and the Gold group to be used ONLY if i'm wearing the 'Brushed Gold' mog. Currently Litemount only seems to mount the group of the highest rule, irrespective of what xmog I'm wearing.

Here is the bug export:
https://pastebin.com/YPfrH3VT

**Comment by mbattersby** [comment] 2023-08-28 00:07
Thanks for this I'll have a look into it as soon as I can.

**Comment by mbattersby** [comment] 2023-08-28 00:32
I'm not sure what to make of this, it looks like it's working from your debug output:

```
Dispatching rule SmartMount [xmog:Blue Reaper,class:PALADIN] Black
 - filters: Black
 - filtered list contains 3 mounts
 - trying Flying Mount
 - found 2 mounts.
 - PriorityRandom n=2, t=0.667, c=0.385
 - setting action to mount Infinite Timereaver
 - found matching rule 7
```

Decoding this:

LiteMount correctly detected that you're a paladin and wearing the Blue Reaper xmog (rule 7 matched).
It attempted to mount something from the "Black" group which contains 3 usable mounts.

You're in a flying area so it restricted to flying mounts and found 2 such mounts, then randomly chose one, Infinite Timereaver.

Which part of this is the bug, what did you expect to happen differently?

**Comment by mbattersby** [comment] 2023-08-28 00:35
Perhaps it is not correct that you were in the Blue Reaper xmog at the time?

**Comment by mbattersby** [comment] 2023-08-28 01:01
xmog: condition is definitely broken and is always returning true for all player-made outfits.

I'll get a fix out as soon as I can do some testing.

**Comment by Sherlockell** [comment] 2023-08-28 01:23
Hey mate, sounds like you've cracked it already.

I tested with multiple different mog sets/groups to be sure but Litemount would always select whatever rule was higher in priority. This logic would seem to make sense, now that you've confirmed any xmog conditional is returning true.

Thanks for looking at this so quickly! ;D

**Comment by mbattersby** [comment] 2023-08-28 01:27
Should be fixed in LiteMount 10.1.5-6 which is packaging itself up now.

**Comment by Sherlockell** [comment] 2023-08-28 02:25
Awesome will test soon and report back!

**Comment by Sherlockell** [comment] 2023-08-28 03:31
Hello again, so good news it seems to be working! Albeit partially. For whatever reason it seems to work once when i first login or on reload. Litemount correctly summons the correct gold mount, from the 'Gold' group while wearing the 'Brushed Gold' mog. However consecutive attempts to mount result in just mounting random mounts from my collection. 

I also tried changing mog to the Blue Reaper which should then let me mount from my 'Black' group but it kept summoning random mounts. This then repeated the same behaviour after a reload, mounting the correct mount in the group before going back to summoning random mounts again.

My rules look like this;
![image](https://github.com/xod-wow/LiteMount/assets/95516063/ba1e429c-10da-4e27-a560-bcba99523201)
![image](https://github.com/xod-wow/LiteMount/assets/95516063/ff1df0b8-19bd-434c-ae47-e017f922bf26)



This is my bug export; https://pastebin.com/HwyWEJxq
And another after i switched to 'Blue reaper' mog: https://pastebin.com/caxjfLq0

Thanks again!

**Comment by mbattersby** [comment] 2023-08-28 04:01
I don't think I can reproduce this one, as far as I can tell it's working consecutively for me.

**Comment by mbattersby** [comment] 2023-08-28 04:13
Here's what I did to try to reproduce it, starting from default rules and no transmog sets.

1. Create a transmog set 'Pink Reaper' which is just a the monk mythic tier (it's pink hence the name).
2. Create a transmog set 'Gold Reaper' which is the monk heroic tier (a bit gold this is a stretch).
3. Add a rule matching Transmog Pink Reaper action Random Mount Swift Pink Hawkstrider.
4. Add a rule matching Transmog Gold Reaper action Random Mount Lightforged Warframe.
5. Apply 'Gold Reaper' transmog.
6. Activate litemount. Do it multiple times. Reload do it some more. Log out and in do it again.
7. No matter what I do always activates Lightforged Warframe.
8. Activate Pink Reaper set.
9. Activate litemount a heap of times. Always summons the Swift Pink Hawkstrider.
10. Switch back to Gold Reaper transmog (no reload or anything since (9).
11. Activate LiteMount. Always summons the Lightforged Warframe.
![image](https://github.com/xod-wow/LiteMount/assets/1300207/6f0dd4e8-a838-4f03-861f-e8c43b83675a)
![image](https://github.com/xod-wow/LiteMount/assets/1300207/eabdd0c3-6402-4611-85ec-33bba1441d0c)

**Comment by Sherlockell** [comment] 2023-08-28 04:17
I can do some more testing, I just tried disabling all addons with only Litemount enabled as I suspected there may be an addon conflict but that didn't seem to help either. The behaviour is the same as I described.

I can stream to you on Discord perhaps if that is easier? or try record whats happening. Not sure how much help that'll be

**Comment by Sherlockell** [comment] 2023-08-28 04:18
Could the fact I'm using 'Smart Priority Mount' potentially cause an issue? I noticed you're using Random Mount

**Comment by mbattersby** [comment] 2023-08-28 04:23
Not by the look of your debug output. I chose that because I'm sitting in Valdrakken and so it would only use Dragonriding mounts with Smart Priority Mount and I wanted the two that obviously matched the names.

From your second debug outfit it just looks like you aren't wearing that xmog any more the second time around. Does it still show as ticked in the outfits menu? Do you have some other addon that might be interfering? Or something that is changing your equipment around?

**Comment by Sherlockell** [comment] 2023-08-28 04:37
Yeah well I run a fair amount of addons so my first step to troubleshoot was to disable them all, but the behaviour persists. it's very strange as I've even moved the rules to the top, like you and can't see what else I would be doing wrong.

These are with all my addons enabled;
![image](https://github.com/xod-wow/LiteMount/assets/95516063/5784a887-adc3-40cc-b6e7-ccac59311bca)
![image](https://github.com/xod-wow/LiteMount/assets/95516063/6f43c814-ec5a-4b04-a0fe-9f715abfbc51)
Bug export: https://pastebin.com/EGxgG8Pv


And this is with all addons except Litemount disabled. Weirdly it works even less for me with everything else disabled, and wont even summon the mount the first time. Just random mounts every time;


![image](https://github.com/xod-wow/LiteMount/assets/95516063/59c09500-c89b-4052-bb71-6c8551892c5d)
Bug export: https://pastebin.com/nDSZDZyi


It's almost like it detects me initially wearing the correct mog, then something happens that makes Litemount think I'm no longer wearing it.

**Comment by mbattersby** [comment] 2023-08-28 04:53
I suepect there is still an issue that the fact that my gear is half what I'm xmogging to anyway is covering up somehow.

**Comment by mbattersby** [comment] 2023-08-28 04:54
Are you able to edit a file? Can you try replacing the IsTransmogOutfitActive function in the file Conditions.lua with this one with extra debug (and one logic change that could be the fix):

```lua
local function IsTransmogOutfitActive(outfitID)
    LM.Debug('Looking for outfit ' .. tostring(outfitID))
    local outfitInfoList = C_TransmogCollection.GetOutfitItemTransmogInfoList(outfitID)
    if not outfitInfoList then return end

    LM.Debug('Found outfit pulling down current equipment xmog')
    local currentInfoList = LM.Environment:GetPlayerTransmogInfo()
    if not currentInfoList then return end

    LM.Debug('Comparing each slot in current equipment')
    for slotID, info in ipairs(currentInfoList) do
        if not info:IsEqual(outfitInfoList[slotID]) then
            if info.appearanceID ~= Constants.Transmog.NoTransmogID then
                LM.Debug(' - slot ' .. slotID .. ' NO MATCH RETURN FALSE')
                return false
            else
                LM.Debug(' - slot ' .. slotID .. ' is NoTransmogID')
            end
        else
            LM.Debug(' - slot ' .. slotID .. ' matches')
        end
    end
    return true
end
```

**Comment by mbattersby** [comment] 2023-08-28 04:57
This is a copy of the whole file with the change in it https://pastebin.com/TnaWcWzT

**Comment by Sherlockell** [comment] 2023-08-28 05:00
Sure one moment

**Comment by Sherlockell** [comment] 2023-08-28 05:04
Still the same issue sadly mate.

![image](https://github.com/xod-wow/LiteMount/assets/95516063/fbcbe817-3ef7-4c3b-814d-cc90d3c8d875)
 Outfit still equipped.
 
 Bug report: https://pastebin.com/di99Qgj8

**Comment by mbattersby** [comment] 2023-08-28 05:08
According to the debug output it believes your main hand weapon does not match the xmog.

**Comment by Sherlockell** [comment] 2023-08-28 05:19
Ok so I think it's working now!! 

After you said it believes the weapon doesn't match the xmog I decided to change the weapon mog, save the mog, then change it back and save it again. Now Litemount appears to be selecting the correct mogs from the correct groups!! :D 

Still very odd how everything from my end and even default blizz UI was saying the mog was equipped, but apparently the equipped mog wasn't matching the outfit mog. Even though it was visually.

Shall I switch back to the old Conditions.lua? or am I good to keep this one? Other than that think you're good to mark this closed. Will be trying plenty mog/mount group combos over the coming days so will report back if any more issues.

Thanks again for your help and time

**Comment by mbattersby** [comment] 2023-08-28 05:28
That is very very strange. I can't say I'm fully happy about it though I'm glad you have something working.

The problem is that as far as I know I'm using exactly the same logic to detect whether the outfit is equipped that Blizzard is using for the check mark on the drop down. I essentially copied it straight from them. I really am at a loss to know how the two things could be different.

You may as well keep the updated Conditions.lua for now. I have another fix to release for transmog (blizzard) sets from other classes so I'll need to put out a new version soon anyway, which will overwrite it. I'll keep the logic change but I'll probably remove the debugging again.

I think you may well have more problems since I don't feel I've gotten to the bottom of this. I'll leave this open for now. Appreciate all your debugging help.

**Comment by Sherlockell** [comment] 2023-08-28 05:41
Just thinking out loud here, but what if the explanation to this is due to saving outfits in other specs. Apparently for the Blizzard logic to show a check mark, you dont actually need to be in that spec. For example, everything was working great for me on ret after re-saving my outfits. Now I've changed to Holy and the check mark still shows, but Litemount doesn't recognise the xmog and my groups no longer work;

![image](https://github.com/xod-wow/LiteMount/assets/95516063/7a18a77d-a73e-4bfa-bf8a-bc7914a2b49a)
![image](https://github.com/xod-wow/LiteMount/assets/95516063/5ec84479-6ec1-4931-b476-fb7ade1a8b44)
Bug report: https://pastebin.com/T1g0Pvrf

Perhaps you could disable the logic that looks for xmog in weapons/sword/shield/offhand and this would fix this issue? Probably easier said than done but I'd imagine this is what's caused it. Maybe I saved the original 'Brushed Gold' mog as Holy all that time ago, so when I was trying to use in in Litemount as Retribution it didn't work. In any case if you are able to disable the check on weapons etc, then I'd appreciate it since I would like to retain Litemount functionality while playing all my specs.

And of course more than happy to continue helping debug/troubleshoot. Although I'm about to sleep for a few hours.

Cheers!

**Comment by Sherlockell** [comment] 2023-08-28 05:42
And switching back to Holy again immediately caused my Litemounts to start working again like before btw

**Comment by mbattersby** [comment] 2023-08-28 05:47
I think the Blizzard logic is just plain wrong :(

![image](https://github.com/xod-wow/LiteMount/assets/1300207/d1b99051-0421-44f8-a4a2-76255aebf44f)

Changed spec and only half in the right gear but it's still checked.

**Comment by mbattersby** [comment] 2023-08-28 11:55
I don't think LiteMount is doing anything wrong. In the sense that it follows the Blizzard logic and checks that every item in your equipment matches the set appearances.

Blizzard has some problems.

They're definitely not updating the appearance check when you respec properly, so the box stays ticked even if you aren't wearing the outfit. I can see this easily myself (e.g., screenshot above) and also if I reselect the outfit from the menu it will apply a bunch of things -- clearly not already applied. In your case the weapon is part of the outfit and you weren't transmogged to it after respeccing, so despite the (buggy) checkbox you aren't wearing that ouftfit.

> Perhaps you could disable the logic that looks for xmog in weapons/sword/shield/offhand and this would fix this issue? 

That's not the problem. In fact that would make things worse since they're part of the set.

I don't know why Blizzard lets you apply a transmog set with a weapon appearance that can't be applied. Or what it does with the "is this set applied or not" check if you do. Clearly if the set appearance is a staff you can't apply that to a 1h mace. They definitely don't exclude any slots in their check that I can see. I suspect it applies what it can but the check will never pass (even if the check box on the menu is buggy).

On the whole, I am leaning towards taking outfit support out. I'm not sure Blizzard have thought it through sufficiently for it to actually work. But I'll keep pondering maybe something will occur.

**Comment by mbattersby** [comment] 2023-08-28 12:13
Weirdly enough it is possible to create an outfit with no weapon it in but just not having one equipped when you save the set. It's a shame there's no UI (at least that I can see) for excluding slots like there is with equipment sets.

Unfortunately the way the Blizzard logic is done that has no effect on whether the outfit "matches" what you're currently wearing or not, and looks like it will make the set only match if you also are not currently wearing a weapon. I can fix that in my code though if it turns out to helpful.

**Comment by Sherlockell** [comment] 2023-08-28 13:46
Afternoon mate, wow it seems like you've done a fair bit of digging overnight.

So I tried editing my 'Brushed Gold' set by removing the weapon mog on the outfit and saving, so that the outfit had a weapon included but it wasn't mogged at all. I then switched to Holy spec and oddly enough the same behaviour came back. Where it would mount the correct mount once, then revert to summoning random mounts.

I then tried make a new mog set called 'Gold' with all weapons removed, but now for whatever reason, that outfit set isn't showing in Litemount to select from;
![image](https://github.com/xod-wow/LiteMount/assets/95516063/fe717b0c-79e9-48b7-9650-0a742d5d6880)
![image](https://github.com/xod-wow/LiteMount/assets/95516063/b99b41b2-6f68-4fa5-8883-76bea94d57f7)
I tried reloading, logging in and out. But still it won't list the new, no weapon 'Gold' outfit, bug export: https://pastebin.com/VxwSxVdp

"Clearly if the outfit appearance is a staff you can't apply that to a 1h mace. They definitely don't exclude any slots in their check that I can see. "

This is true for normal weapons, but for Artifact appearances, I believe you can mog 1H's to things like staffs and vice versa


Like you said, It seems Blizzards logic for how they decide whether an outfit is equipped or not seems broken. However I would really like to retain this feature if possible, as it does work now, albeit partially, provided I don't change spec once the mog's equipped. 

Is there anyway you can make Litemount ignore the weapon/shield mog check? And instead return true to the mog being equipped if all other slots are present? I think for most users it will only ever be the weapons that change when they change spec. Or they will change to a different mog entirely for the other spec and therefore can/will summon mounts from a different ruleset and group.

Around all day to be a test bitch if you need me to try anything, and thanks again :D

**Comment by Sherlockell** [comment] 2023-08-28 13:54
Actually, it appears both the 2 new mog outfits I made are not appearing in the list of outfits in Litemount. 

![image](https://github.com/xod-wow/LiteMount/assets/95516063/f1f29ac7-c6ee-482a-b39e-1f3228907867)
![image](https://github.com/xod-wow/LiteMount/assets/95516063/df27711b-7ffe-44ce-bada-b9d40b0bfa53)

**Comment by mbattersby** [comment] 2023-08-29 03:38
Blizzard supports a maximum of 20 outfits. You can't create or store more than that. It's not surprising that your 21st and 22nd outfits don't show. Whatever other addons you are using are obviously enhancing the outfit interface somehow. I'm afraid whatever that is I can't support it.

![image](https://github.com/xod-wow/LiteMount/assets/1300207/225a083f-832e-4d60-8808-39b8083f5d39)
Add outfit button is gone after 20 are created.

**Comment by mbattersby** [comment] 2023-08-29 03:49
> Is there anyway you can make Litemount ignore the weapon/shield mog check? And instead return true to the mog being equipped if all other slots are present? I think for most users it will only ever be the weapons that change when they change spec. Or they will change to a different mog entirely for the other spec and therefore can/will summon mounts from a different ruleset and group.

I think this is probably a reasonable approach without any Blizzard support for excluding slots from outfits, since it mostly matches up with how people will think about the premade sets which don't include weapons or offhands.

I'm going to ponder this a bit, and facing the sad reality of having a job and a minimum semblance of a life I probably won't have anything new to report until the weekend.

This is my best untested guess at a replacement IsTransmogOutfitActive function that would exclude main/offhand:

```lua
-- This makes me want to kill myself instantly.
-- See WardrobeOutfitDropDownMixin:IsOutfitDressed()

local ExcludeOutfitSlot = {
    INVSLOT_MAINHAND = true, INVSLOT_OFFHAND = true, INVSLOT_RANGED = true,
}

local function IsTransmogOutfitActive(outfitID)
    local outfitInfoList = C_TransmogCollection.GetOutfitItemTransmogInfoList(outfitID)
    if not outfitInfoList then return end

    local currentInfoList = LM.Environment:GetPlayerTransmogInfo()
    if not currentInfoList then return end

    for slotID, info in ipairs(outfitInfoList) do
        if not ExcludeOutfitSlot[slotID] and not info:IsEqual(currentInfoList[slotID]) then
            if info.appearanceID ~= Constants.Transmog.NoTransmogID then
                return false
            end
        end
    end
    return true
end
```

**Comment by Sherlockell** [comment] 2023-08-30 03:26
Hey mate apologies only just got around to testing.

You were correct, I think a transmog addon I had extends past the default 20 outfits. Needed to cut down on some of them anyway ;D

The change you made above seems to be working perfectly! Although it's not an ideal solution I appreciate you taking the time to ship a workaround. Suppose I shouldn't be surprised that Blizzards shoddy code made this such a headache, but hopefully, other users will be happy with this change/fix too.

Will report if I come across any issues but thanks again

**Comment by mbattersby** [comment] 2023-08-30 07:13
Thanks for checking. It doesn't seem to have caused any issues, but I'll let it run a bit longer and hopefully put out a release with it included on Friday or Saturday.

**Comment by mbattersby** [comment] 2023-09-01 06:17
Should be there in 10.5.1-8. Thanks again for your help.

**Closed by mbattersby** 2023-09-01 06:17 UTC
